const { withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');

// react-native-background-upload bundles `net.gotev:uploadservice:4.7.0`, which
// runs every upload inside a foreground Service and calls the two-arg
// `startForeground(id, notification)` — with no `android:foregroundServiceType`.
// On Android 14+ (targetSdk >= 34, which Expo 56 uses) that throws
// `MissingForegroundServiceTypeException`: the upload service dies the instant
// it starts, so the JS layer never receives a single progress/completed/error
// event and the chat voice / video upload sits frozen at 0% forever.
//
// The library's own AndroidManifest can't be edited (it's inside an AAR), so
// this merges the missing attribute onto its <service> node via the manifest
// merger and adds the matching runtime permission. "dataSync" is the correct
// type for an app-initiated network upload that must briefly outlive the UI.
//
// Ships as a config-plugin (not a hand edit to android/) because android/ is
// regenerated by `expo prebuild` on every EAS build.
const UPLOAD_SERVICE = 'net.gotev.uploadservice.UploadService';
const FGS_TYPE = 'dataSync';
const FGS_PERMISSION = 'android.permission.FOREGROUND_SERVICE_DATA_SYNC';

module.exports = function withUploadServiceForegroundType(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults;

    // 1. Runtime permission required to start a dataSync foreground service on API 34+.
    manifest.manifest['uses-permission'] = manifest.manifest['uses-permission'] ?? [];
    const hasPerm = manifest.manifest['uses-permission'].some(
      (p) => p.$?.['android:name'] === FGS_PERMISSION,
    );
    if (!hasPerm) {
      manifest.manifest['uses-permission'].push({ $: { 'android:name': FGS_PERMISSION } });
    }

    // 2. Merge android:foregroundServiceType onto the library's <service>.
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
    application.service = application.service ?? [];

    let service = application.service.find((s) => s.$?.['android:name'] === UPLOAD_SERVICE);
    if (!service) {
      service = { $: { 'android:name': UPLOAD_SERVICE } };
      application.service.push(service);
    }
    service.$['android:foregroundServiceType'] = FGS_TYPE;
    // Default merge behaviour already adds the attribute to the AAR's node; be explicit.
    service.$['tools:node'] = 'merge';

    return config;
  });
};
