const { withAppBuildGradle } = require('@expo/config-plugins');

// react-native-background-upload@6.6.0 hard-pins `net.gotev:uploadservice-okhttp:4.7.0`
// in its own android/build.gradle. That version registers the notification-action
// BroadcastReceiver (net.gotev.uploadservice.observer.request.NotificationActionsObserver)
// with the two-arg `Context.registerReceiver(receiver, filter)`.
//
// On Android 14 (targetSdk >= 34, which Expo 56 uses) that call throws
//   SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be
//   specified when a receiver isn't being registered exclusively for system broadcasts
// from UploadService.onCreate(), so the very first chat voice / video upload
// crashes the app (confirmed on Xiaomi / Android 14, Sentry).
//
// gotev/android-upload-service fixed this in 4.9.0 ("Support for Android 14") and
// 4.9.3 ("Fixed receiver not exported"); 4.9.4 is the latest 4.x. The 4.7 -> 4.9
// changes are pure compatibility patches — no changes to the handful of APIs the
// Vydia wrapper compiles against (UploadServiceConfig.initialize, GlobalRequestObserver,
// UploadService.stopUpload, OkHttpStack, Binary/MultipartUploadRequest) — so bumping
// the runtime classpath is binary-safe even though the wrapper still *compiles*
// against 4.7.0 headers.
//
// The wrapper's build.gradle lives inside node_modules and android/ is regenerated
// by `expo prebuild` on every EAS build, so this has to be a config plugin: it
// forces the resolved version of both gotev artifacts on every Gradle configuration.
//
// This also makes ./plugins/withUploadServiceForegroundType.js partly redundant
// (4.9.2+ sets the foreground-service type itself) but that plugin is harmless to
// keep — it merges the same `dataSync` value.
const FORCED_VERSION = '4.9.4';

const FORCE_BLOCK = `
// @generated by ./plugins/withForceUploadServiceVersion.js — do not edit
configurations.all {
    resolutionStrategy {
        force "net.gotev:uploadservice:${FORCED_VERSION}"
        force "net.gotev:uploadservice-okhttp:${FORCED_VERSION}"
    }
}
`;

module.exports = function withForceUploadServiceVersion(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        'withForceUploadServiceVersion: expected android/app/build.gradle to be Groovy',
      );
    }
    if (!config.modResults.contents.includes('withForceUploadServiceVersion.js')) {
      config.modResults.contents += `\n${FORCE_BLOCK}`;
    }
    return config;
  });
};
