ALTER TABLE "creator_profiles" ADD COLUMN IF NOT EXISTS "prefPlatforms" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "creator_profiles" ADD COLUMN IF NOT EXISTS "prefLocations" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "creator_profiles" ADD COLUMN IF NOT EXISTS "prefBudgetMin" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "creator_profiles" ADD COLUMN IF NOT EXISTS "prefBudgetMax" DOUBLE PRECISION NOT NULL DEFAULT 500;
