-- The preceding migration (add_provider_marketplace_fields) was generated by
-- `prisma migrate dev`, which diffed the live DB against schema.prisma and
-- dropped these four indexes because they're raw-SQL-managed (GIN/trigram,
-- see 20260722103717_add_campaign_fulltext_search) and therefore invisible to
-- schema.prisma — Prisma's diff engine treats anything it can't model as
-- drift to remove. Restoring them here. NOTE: any future `prisma migrate dev`
-- run will attempt to drop these again for the same reason — always inspect
-- the generated migration.sql for stray "DROP INDEX ..._trgm_idx" /
-- "DROP INDEX campaigns_searchVector_idx" lines before applying, and delete
-- those lines from the generated file if present.

CREATE INDEX IF NOT EXISTS "campaigns_searchVector_idx" ON "campaigns" USING GIN ("searchVector");
CREATE INDEX IF NOT EXISTS "campaigns_title_trgm_idx" ON "campaigns" USING GIN (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "campaigns_category_trgm_idx" ON "campaigns" USING GIN (category gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "business_profiles_businessName_trgm_idx" ON "business_profiles" USING GIN ("businessName" gin_trgm_ops);
