-- Supports BusinessRepository.findManySearch's broadened creator-discover
-- search (see that method's comment): businessName already had a trigram
-- index (business_profiles_businessName_trgm_idx), description didn't, so an
-- ILIKE '%term%' / similarity() match against description fell back to a
-- sequential scan. Same GIN + gin_trgm_ops shape as the existing index —
-- pg_trgm is already enabled (20260722103717_add_campaign_fulltext_search).
--
-- NOTE: like every other raw-SQL-managed index in this file's siblings
-- (20260814130000_restore_search_indexes and its follow-ups), `prisma
-- migrate dev` will treat this as drift and try to DROP it on the next
-- schema change since schema.prisma can't model it. Inspect generated
-- migration.sql for a stray "DROP INDEX business_profiles_description_trgm_idx"
-- line before applying, and delete it if present.
CREATE INDEX IF NOT EXISTS "business_profiles_description_trgm_idx" ON "business_profiles" USING GIN (description gin_trgm_ops);
