import { MapPin } from 'lucide-react';
import type { NicheConfig } from './NichePage';

// One entry per "influencers <city>" keyword cluster. Bilingual: `label` is
// the short niche label plugged into shared.ts's templated benefits/steps/
// FAQs, and `en`/`ne` hold the page-specific copy (SEO meta is left
// identical between languages — only visible content is translated).
export const CITY_PAGES: NicheConfig[] = [
  {
    slug: 'influencers-kathmandu',
    icon: MapPin,
    keywords: ['influencers Kathmandu', 'content creators Kathmandu', 'Kathmandu influencer marketing', 'hire influencer Kathmandu'],
    label: { en: 'Kathmandu creators', ne: 'काठमाडौं क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Kathmandu | Hire Kathmandu Content Creators',
      seoDescription: "Find and hire influencers and content creators in Kathmandu on Kolab — Nepal's capital and its largest creator community, across every platform and niche.",
      breadcrumbName: 'Kathmandu Influencers',
      eyebrow: 'Influencers in Kathmandu',
      heading: 'Influencers in Kathmandu',
      intro: "As Nepal's capital and largest city, Kathmandu is home to the country's biggest and most active creator community — spanning every platform and niche from fashion to food to tech.",
      overviewHeading: "Kathmandu's creator scene",
      overviewParagraphs: [
        "Kathmandu is where most of Nepal's brands, agencies, and creators are based, which makes it the single largest market on Kolab for finding influencers — whether you need a fashion creator in Thamel, a food reviewer covering New Road's cafes, or a tech creator unboxing the latest phone.",
        'Because so much of Nepal\'s digital economy runs through Kathmandu, brands based here also have the widest pool of creators to choose from across categories, platforms, and follower sizes.',
      ],
      secondHeading: 'Creators across every niche in Kathmandu',
      secondParagraphs: [
        'Kathmandu creators on Kolab cover Food & Beverage, Fashion, Beauty, Technology, Fitness, and nearly every other category, across Instagram, TikTok, YouTube, and Facebook.',
        'Businesses based in Kathmandu — or brands elsewhere looking to reach the capital\'s audience — can filter creator search by location to find creators actually based in or covering the city.',
      ],
      trustParagraph: 'Every creator on Kolab, in Kathmandu or anywhere else in Nepal, goes through the same identity verification and escrow-protected payment process, so scale doesn\'t come at the cost of trust.',
      faqsExtra: [
        { question: 'Can I search for creators based specifically in Kathmandu?', answer: 'Yes — creator profiles include location, so you can filter for Kathmandu-based creators alongside category and platform when browsing or posting a campaign.' },
      ],
      relatedExtra: { label: 'Pokhara Influencers', path: '/influencers-pokhara', description: 'Explore creators based in Pokhara.' },
      ctaHeading: 'Find Influencers in Kathmandu',
      ctaSub: 'Download Kolab to connect with Kathmandu creators.',
    },
    ne: {
      seoTitle: 'Influencers in Kathmandu | Hire Kathmandu Content Creators',
      seoDescription: "Find and hire influencers and content creators in Kathmandu on Kolab — Nepal's capital and its largest creator community, across every platform and niche.",
      breadcrumbName: 'काठमाडौं इन्फ्लुएन्सरहरू',
      eyebrow: 'काठमाडौंका इन्फ्लुएन्सरहरू',
      heading: 'काठमाडौंका इन्फ्लुएन्सरहरू',
      intro: 'नेपालको राजधानी र सबैभन्दा ठूलो सहरको रूपमा, काठमाडौं देशको सबैभन्दा ठूलो र सक्रिय क्रिएटर समुदायको घर हो — फेसनदेखि खाना र प्रविधिसम्म हरेक प्लेटफर्म र निच समेट्दै।',
      overviewHeading: 'काठमाडौंको क्रिएटर दृश्य',
      overviewParagraphs: [
        'काठमाडौं नै हो जहाँ नेपालका धेरैजसो ब्रान्ड, एजेन्सी, र क्रिएटरहरू आधारित छन्, जसले यसलाई Kolab मा इन्फ्लुएन्सर फेला पार्ने सबैभन्दा ठूलो बजार बनाउँछ — चाहे तपाईंलाई थमेलमा फेसन क्रिएटर चाहिएको होस्, न्यू रोडका क्याफेहरू कभर गर्ने खाना समीक्षक चाहिएको होस्, वा नयाँ फोन अनबक्स गर्ने टेक क्रिएटर चाहिएको होस्।',
        'नेपालको डिजिटल अर्थतन्त्रको धेरैजसो भाग काठमाडौंमार्फत चल्ने भएकाले, यहाँ आधारित ब्रान्डहरूसँग पनि श्रेणी, प्लेटफर्म, र फलोअर संख्याअनुसार छनोट गर्न सबैभन्दा फराकिलो क्रिएटर समूह हुन्छ।',
      ],
      secondHeading: 'काठमाडौंमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा काठमाडौंका क्रिएटरहरूले Instagram, TikTok, YouTube, र Facebook मा खाना र पेय, फेसन, ब्युटी, प्रविधि, फिटनेस, र लगभग हरेक अन्य श्रेणी समेट्छन्।',
        'काठमाडौंमा आधारित व्यवसायहरू — वा राजधानीको दर्शकसम्म पुग्न चाहने अन्यत्रका ब्रान्डहरू — सहरमा साँच्चै आधारित वा सहर कभर गर्ने व्यक्तिहरू फेला पार्न स्थान अनुसार क्रिएटर खोज फिल्टर गर्न सक्छन्।',
      ],
      trustParagraph: 'काठमाडौं वा नेपालको अन्य जुनसुकै ठाउँका Kolab का हरेक क्रिएटरले उही पहिचान प्रमाणीकरण र एस्क्रो-सुरक्षित भुक्तानी प्रक्रियाबाट गुज्रन्छन्, त्यसैले स्तरले भरोसाको मूल्य चुकाउनु पर्दैन।',
      faqsExtra: [
        { question: 'के म विशेष गरी काठमाडौंमा आधारित क्रिएटरहरू खोज्न सक्छु?', answer: 'हो — क्रिएटर प्रोफाइलहरूमा स्थान समावेश हुन्छ, त्यसैले ब्राउज गर्दा वा क्याम्पेन पोस्ट गर्दा तपाईंले श्रेणी र प्लेटफर्मसँगै काठमाडौं-आधारित क्रिएटरहरूका लागि फिल्टर गर्न सक्नुहुन्छ।' },
      ],
      relatedExtra: { label: 'पोखरा इन्फ्लुएन्सरहरू', path: '/influencers-pokhara', description: 'पोखरामा आधारित क्रिएटरहरू अन्वेषण गर्नुहोस्।' },
      ctaHeading: 'काठमाडौंमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'काठमाडौंका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-pokhara',
    icon: MapPin,
    keywords: ['influencers Pokhara', 'content creators Pokhara', 'Pokhara influencer marketing', 'hire influencer Pokhara'],
    label: { en: 'Pokhara creators', ne: 'पोखरा क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Pokhara | Hire Pokhara Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Pokhara on Kolab — Nepal\'s tourism hub, strong for travel, hospitality, and lifestyle content.',
      breadcrumbName: 'Pokhara Influencers',
      eyebrow: 'Influencers in Pokhara',
      heading: 'Influencers in Pokhara',
      intro: "Lakeside cafes, adventure sports, and mountain views make Pokhara Nepal's tourism capital — and its creators are some of the strongest travel and lifestyle content producers in the country.",
      overviewHeading: "Pokhara's creator scene",
      overviewParagraphs: [
        "Pokhara's economy leans heavily on tourism, and its creators reflect that — many post travel vlogs, hotel and cafe reviews, and adventure content (paragliding, boating on Phewa Lake, trekking access points) that performs well with both domestic and international audiences.",
        "Hotels, resorts, travel agencies, and adventure-sports operators in and around Pokhara can find creators on Kolab who already document the city and its surroundings.",
      ],
      secondHeading: 'Creators across every niche in Pokhara',
      secondParagraphs: [
        'Beyond travel, Pokhara creators on Kolab also cover Food & Beverage, Lifestyle, and Fitness, giving local businesses outside tourism a way to find relevant creators too.',
        'Brands elsewhere in Nepal can also target Pokhara-based creators for campaigns aimed at the city\'s tourism and hospitality audience.',
      ],
      trustParagraph: 'Pokhara creator partnerships — including hotel stays and adventure-activity collaborations — run through the same verified-creator, escrow-protected process as every location on Kolab.',
      faqsExtra: [
        { question: 'Is Pokhara good for travel and hospitality campaigns specifically?', answer: 'Yes — Pokhara has one of the strongest concentrations of travel, hotel, and lifestyle creators on Kolab, making it a strong fit for tourism-related campaigns.' },
      ],
      relatedExtra: { label: 'Travel Influencers', path: '/travel-influencers-nepal', description: 'Browse travel creators covering destinations across Nepal.' },
      ctaHeading: 'Find Influencers in Pokhara',
      ctaSub: 'Download Kolab to connect with Pokhara creators.',
    },
    ne: {
      seoTitle: 'Influencers in Pokhara | Hire Pokhara Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Pokhara on Kolab — Nepal\'s tourism hub, strong for travel, hospitality, and lifestyle content.',
      breadcrumbName: 'पोखरा इन्फ्लुएन्सरहरू',
      eyebrow: 'पोखराका इन्फ्लुएन्सरहरू',
      heading: 'पोखराका इन्फ्लुएन्सरहरू',
      intro: 'तालकिनारका क्याफे, साहसिक खेलकुद, र हिमाली दृश्यले पोखरालाई नेपालको पर्यटन राजधानी बनाउँछ — र यहाँका क्रिएटरहरू देशकै सबैभन्दा बलियो ट्राभल र लाइफस्टाइल सामग्री उत्पादक मध्ये पर्छन्।',
      overviewHeading: 'पोखराको क्रिएटर दृश्य',
      overviewParagraphs: [
        'पोखराको अर्थतन्त्र धेरै हदसम्म पर्यटनमा निर्भर छ, र यहाँका क्रिएटरहरूले त्यही झल्काउँछन् — धेरैले ट्राभल भ्लग, होटल र क्याफे समीक्षा, र साहसिक सामग्री (प्याराग्लाइडिङ, फेवा तालमा डुङ्गा सयर, ट्रेकिङ पहुँच विन्दुहरू) पोस्ट गर्छन्, जसले स्वदेशी र अन्तर्राष्ट्रिय दुवै दर्शकसँग राम्रो प्रदर्शन गर्छ।',
        'पोखरा र वरपरका होटल, रिसोर्ट, ट्राभल एजेन्सी, र साहसिक-खेलकुद सञ्चालकहरूले Kolab मा सहर र यसका वरपरका क्षेत्रहरू पहिले नै डकुमेन्ट गरिरहेका क्रिएटरहरू फेला पार्न सक्छन्।',
      ],
      secondHeading: 'पोखरामा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'ट्राभल बाहेक, Kolab मा पोखराका क्रिएटरहरूले खाना र पेय, लाइफस्टाइल, र फिटनेस पनि समेट्छन्, जसले पर्यटन बाहेकका स्थानीय व्यवसायहरूलाई पनि उपयुक्त क्रिएटर फेला पार्ने बाटो दिन्छ।',
        'नेपालका अन्य ठाउँका ब्रान्डहरूले पनि सहरको पर्यटन र आतिथ्य दर्शकलाई लक्षित गर्ने क्याम्पेनका लागि पोखरा-आधारित क्रिएटरहरूलाई लक्षित गर्न सक्छन्।',
      ],
      trustParagraph: 'पोखरा क्रिएटर साझेदारीहरू — होटल बसाइ र साहसिक-गतिविधि सहकार्यहरू सहित — Kolab को हरेक स्थानमा जस्तै उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट चल्छन्।',
      faqsExtra: [
        { question: 'के पोखरा विशेष गरी ट्राभल र आतिथ्य क्याम्पेनका लागि राम्रो हो?', answer: 'हो — पोखरामा Kolab मा ट्राभल, होटल, र लाइफस्टाइल क्रिएटरहरूको सबैभन्दा बलियो सघनता छ, जसले यसलाई पर्यटन-सम्बन्धित क्याम्पेनका लागि उपयुक्त बनाउँछ।' },
      ],
      relatedExtra: { label: 'ट्राभल इन्फ्लुएन्सरहरू', path: '/travel-influencers-nepal', description: 'नेपालभरका गन्तव्यहरू कभर गर्ने ट्राभल क्रिएटरहरू ब्राउज गर्नुहोस्।' },
      ctaHeading: 'पोखरामा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'पोखराका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-lalitpur',
    icon: MapPin,
    keywords: ['influencers Lalitpur', 'content creators Lalitpur', 'Patan influencers', 'hire influencer Lalitpur'],
    label: { en: 'Lalitpur creators', ne: 'ललितपुर क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Lalitpur | Hire Lalitpur (Patan) Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Lalitpur (Patan) on Kolab — strong for arts, design, and Newari culture content in the Kathmandu Valley.',
      breadcrumbName: 'Lalitpur Influencers',
      eyebrow: 'Influencers in Lalitpur',
      heading: 'Influencers in Lalitpur',
      intro: "Lalitpur (Patan) blends Newari heritage with a modern arts, design, and cafe scene, giving its creators a distinct visual identity within the Kathmandu Valley.",
      overviewHeading: "Lalitpur's creator scene",
      overviewParagraphs: [
        "Home to Patan Durbar Square, artisan workshops, and a growing number of design studios and boutique cafes, Lalitpur has developed a creator community that leans into art, craft, fashion, and aesthetic-driven content.",
        'Kolab connects brands — from local designers to cafes to lifestyle stores — with creators based in Lalitpur who already produce content in that visual register.',
      ],
      secondHeading: 'Creators across every niche in Lalitpur',
      secondParagraphs: [
        'Lalitpur creators on Kolab span Art & Design, Fashion, Food & Beverage, and Lifestyle, alongside general categories, across Instagram and TikTok.',
        'Because Lalitpur sits within the greater Kathmandu Valley, campaigns here often reach much of the same audience as Kathmandu while tapping a distinct creator aesthetic.',
      ],
      trustParagraph: 'Lalitpur creator collaborations follow the same identity verification and escrow-protected payment process as every location on Kolab.',
      relatedExtra: { label: 'Kathmandu Influencers', path: '/influencers-kathmandu', description: 'Explore creators across the wider Kathmandu Valley.' },
      ctaHeading: 'Find Influencers in Lalitpur',
      ctaSub: 'Download Kolab to connect with Lalitpur creators.',
    },
    ne: {
      seoTitle: 'Influencers in Lalitpur | Hire Lalitpur (Patan) Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Lalitpur (Patan) on Kolab — strong for arts, design, and Newari culture content in the Kathmandu Valley.',
      breadcrumbName: 'ललितपुर इन्फ्लुएन्सरहरू',
      eyebrow: 'ललितपुरका इन्फ्लुएन्सरहरू',
      heading: 'ललितपुरका इन्फ्लुएन्सरहरू',
      intro: 'ललितपुर (पाटन) ले नेवारी सम्पदालाई आधुनिक कला, डिजाइन, र क्याफे दृश्यसँग मिसाउँछ, जसले यहाँका क्रिएटरहरूलाई काठमाडौं उपत्यकाभित्र छुट्टै भिजुअल पहिचान दिन्छ।',
      overviewHeading: 'ललितपुरको क्रिएटर दृश्य',
      overviewParagraphs: [
        'पाटन दरबार क्षेत्र, कारीगर कार्यशालाहरू, र बढ्दो संख्यामा डिजाइन स्टुडियो र बुटिक क्याफेको घर, ललितपुरले कला, शिल्प, फेसन, र सौन्दर्य-केन्द्रित सामग्रीतर्फ झुकेको क्रिएटर समुदाय विकास गरेको छ।',
        'Kolab ले स्थानीय डिजाइनरदेखि क्याफे र लाइफस्टाइल पसलसम्मका ब्रान्डहरूलाई त्यही भिजुअल शैलीमा सामग्री बनाइरहेका ललितपुर-आधारित क्रिएटरहरूसँग जोड्छ।',
      ],
      secondHeading: 'ललितपुरमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा ललितपुरका क्रिएटरहरूले सामान्य श्रेणीहरूसँगै Instagram र TikTok मा कला र डिजाइन, फेसन, खाना र पेय, र लाइफस्टाइल समेट्छन्।',
        'ललितपुर ठूलो काठमाडौं उपत्यकाभित्रै पर्ने भएकाले, यहाँका क्याम्पेनहरूले प्रायः काठमाडौंकै जस्तो धेरैजसो दर्शकसम्म पुग्छन्, साथै छुट्टै क्रिएटर सौन्दर्यको फाइदा पनि लिन्छन्।',
      ],
      trustParagraph: 'ललितपुर क्रिएटर सहकार्यहरूले Kolab को हरेक स्थानमा जस्तै उही पहिचान प्रमाणीकरण र एस्क्रो-सुरक्षित भुक्तानी प्रक्रिया पछ्याउँछन्।',
      relatedExtra: { label: 'काठमाडौं इन्फ्लुएन्सरहरू', path: '/influencers-kathmandu', description: 'ठूलो काठमाडौं उपत्यकाभरका क्रिएटरहरू अन्वेषण गर्नुहोस्।' },
      ctaHeading: 'ललितपुरमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'ललितपुरका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-bhaktapur',
    icon: MapPin,
    keywords: ['influencers Bhaktapur', 'content creators Bhaktapur', 'Bhaktapur influencer marketing', 'hire influencer Bhaktapur'],
    label: { en: 'Bhaktapur creators', ne: 'भक्तपुर क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Bhaktapur | Hire Bhaktapur Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Bhaktapur on Kolab — a UNESCO heritage city strong for culture, craft, and tourism content.',
      breadcrumbName: 'Bhaktapur Influencers',
      eyebrow: 'Influencers in Bhaktapur',
      heading: 'Influencers in Bhaktapur',
      intro: "Bhaktapur's UNESCO-listed heritage squares and pottery traditions make it one of Nepal's most photographed cities — and a strong base for culture, craft, and tourism-focused creators.",
      overviewHeading: "Bhaktapur's creator scene",
      overviewParagraphs: [
        "Bhaktapur draws heavy domestic and international tourist traffic to its Durbar Square, Pottery Square, and traditional Newari architecture, and its creators often produce heritage, food (like the city's famous juju dhau), and craft content built around that setting.",
        'Kolab connects heritage-tourism operators, craft brands, and local cafes with creators based in Bhaktapur who already cover the city.',
      ],
      secondHeading: 'Creators across every niche in Bhaktapur',
      secondParagraphs: [
        'Bhaktapur creators on Kolab post under Travel, Food & Beverage, and Art & Design, alongside general lifestyle content, across Instagram and YouTube.',
        'Brands running heritage-tourism or craft-focused campaigns can specifically target Bhaktapur-based creators for authentic, location-grounded content.',
      ],
      trustParagraph: 'Bhaktapur creator partnerships run through the same verified-creator, escrow-protected process as every location on Kolab.',
      relatedExtra: { label: 'Food Influencers', path: '/food-influencers-nepal', description: "Bhaktapur's food and craft content overlaps closely with this category." },
      ctaHeading: 'Find Influencers in Bhaktapur',
      ctaSub: 'Download Kolab to connect with Bhaktapur creators.',
    },
    ne: {
      seoTitle: 'Influencers in Bhaktapur | Hire Bhaktapur Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Bhaktapur on Kolab — a UNESCO heritage city strong for culture, craft, and tourism content.',
      breadcrumbName: 'भक्तपुर इन्फ्लुएन्सरहरू',
      eyebrow: 'भक्तपुरका इन्फ्लुएन्सरहरू',
      heading: 'भक्तपुरका इन्फ्लुएन्सरहरू',
      intro: 'भक्तपुरको युनेस्को-सूचीकृत सम्पदा चोक र माटोका भाँडा बनाउने परम्पराले यसलाई नेपालकै सबैभन्दा धेरै फोटो खिचिने सहरहरू मध्ये एक बनाउँछ — र संस्कृति, शिल्प, र पर्यटन-केन्द्रित क्रिएटरहरूको लागि बलियो आधार पनि।',
      overviewHeading: 'भक्तपुरको क्रिएटर दृश्य',
      overviewParagraphs: [
        'भक्तपुरले आफ्नो दरबार क्षेत्र, पोटरी चोक, र परम्परागत नेवारी वास्तुकलामा ठूलो संख्यामा स्वदेशी र अन्तर्राष्ट्रिय पर्यटक तान्छ, र यहाँका क्रिएटरहरूले प्रायः त्यही परिवेशमा आधारित सम्पदा, खाना (सहरको प्रसिद्ध जुजु धौ जस्तै), र शिल्प सामग्री बनाउँछन्।',
        'Kolab ले सम्पदा-पर्यटन सञ्चालक, शिल्प ब्रान्ड, र स्थानीय क्याफेहरूलाई सहर पहिले नै कभर गरिरहेका भक्तपुर-आधारित क्रिएटरहरूसँग जोड्छ।',
      ],
      secondHeading: 'भक्तपुरमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा भक्तपुरका क्रिएटरहरूले सामान्य लाइफस्टाइल सामग्रीसँगै Instagram र YouTube मा ट्राभल, खाना र पेय, र कला र डिजाइन अन्तर्गत पोस्ट गर्छन्।',
        'सम्पदा-पर्यटन वा शिल्प-केन्द्रित क्याम्पेन चलाउने ब्रान्डहरूले प्रामाणिक, स्थान-आधारित सामग्रीका लागि विशेष गरी भक्तपुर-आधारित क्रिएटरहरूलाई लक्षित गर्न सक्छन्।',
      ],
      trustParagraph: 'भक्तपुर क्रिएटर साझेदारीहरू Kolab को हरेक स्थानमा जस्तै उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट चल्छन्।',
      relatedExtra: { label: 'फुड इन्फ्लुएन्सरहरू', path: '/food-influencers-nepal', description: 'भक्तपुरको खाना र शिल्प सामग्री यो श्रेणीसँग नजिकबाट मिल्दोजुल्दो छ।' },
      ctaHeading: 'भक्तपुरमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'भक्तपुरका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-chitwan',
    icon: MapPin,
    keywords: ['influencers Chitwan', 'content creators Chitwan', 'Chitwan influencer marketing', 'hire influencer Chitwan'],
    label: { en: 'Chitwan creators', ne: 'चितवन क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Chitwan | Hire Chitwan Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Chitwan on Kolab — strong for wildlife tourism, jungle safari, and nature content.',
      breadcrumbName: 'Chitwan Influencers',
      eyebrow: 'Influencers in Chitwan',
      heading: 'Influencers in Chitwan',
      intro: "Home to Chitwan National Park, jungle safaris, and a growing resort scene, Chitwan gives brands access to creators who specialize in wildlife tourism and nature content.",
      overviewHeading: "Chitwan's creator scene",
      overviewParagraphs: [
        "Chitwan's identity as Nepal's premier wildlife-tourism destination — rhino sightings, jungle safaris, Tharu cultural shows — has shaped a creator community focused on nature and experiential travel content.",
        'Resorts, safari operators, and eco-tourism brands based in or around Bharatpur and the national park area can connect with Chitwan creators through Kolab.',
      ],
      secondHeading: 'Creators across every niche in Chitwan',
      secondParagraphs: [
        'Chitwan creators on Kolab post primarily under Travel, alongside Food & Beverage and Lifestyle, across Instagram and YouTube.',
        'Wildlife lodges and safari operators can offer a free open event — a stay or safari experience in exchange for content — as an alternative to a fixed paid budget.',
      ],
      trustParagraph: 'Stay-for-content and paid campaigns in Chitwan run through the same verified-creator, escrow-protected process as every location on Kolab.',
      relatedExtra: { label: 'Travel Influencers', path: '/travel-influencers-nepal', description: 'Browse travel creators covering destinations across Nepal.' },
      ctaHeading: 'Find Influencers in Chitwan',
      ctaSub: 'Download Kolab to connect with Chitwan creators.',
    },
    ne: {
      seoTitle: 'Influencers in Chitwan | Hire Chitwan Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Chitwan on Kolab — strong for wildlife tourism, jungle safari, and nature content.',
      breadcrumbName: 'चितवन इन्फ्लुएन्सरहरू',
      eyebrow: 'चितवनका इन्फ्लुएन्सरहरू',
      heading: 'चितवनका इन्फ्लुएन्सरहरू',
      intro: 'चितवन राष्ट्रिय निकुञ्ज, जंगल सफारी, र बढ्दो रिसोर्ट दृश्यको घर, चितवनले ब्रान्डहरूलाई वन्यजन्तु पर्यटन र प्रकृति सामग्रीमा विशेषज्ञता भएका क्रिएटरहरूसम्म पहुँच दिन्छ।',
      overviewHeading: 'चितवनको क्रिएटर दृश्य',
      overviewParagraphs: [
        'नेपालको प्रमुख वन्यजन्तु-पर्यटन गन्तव्यको रूपमा चितवनको पहिचान — गैंडा देखावट, जंगल सफारी, थारू सांस्कृतिक कार्यक्रमहरू — ले प्रकृति र अनुभवमूलक ट्राभल सामग्रीमा केन्द्रित क्रिएटर समुदाय निर्माण गरेको छ।',
        'भरतपुर र राष्ट्रिय निकुञ्ज क्षेत्र वरपर आधारित रिसोर्ट, सफारी सञ्चालक, र इको-पर्यटन ब्रान्डहरूले Kolab मार्फत चितवनका क्रिएटरहरूसँग जोडिन सक्छन्।',
      ],
      secondHeading: 'चितवनमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा चितवनका क्रिएटरहरूले खाना र पेय र लाइफस्टाइलसँगै मुख्यतः Instagram र YouTube मा ट्राभल अन्तर्गत पोस्ट गर्छन्।',
        'वन्यजन्तु लज र सफारी सञ्चालकहरूले निश्चित तलबसहितको बजेटको सट्टा — सामग्रीको बदलामा बसाइ वा सफारी अनुभव दिने — निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छन्।',
      ],
      trustParagraph: 'चितवनमा सामग्रीको बदलामा बसाइ र तलबसहितका क्याम्पेनहरू Kolab को हरेक स्थानमा जस्तै उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट चल्छन्।',
      relatedExtra: { label: 'ट्राभल इन्फ्लुएन्सरहरू', path: '/travel-influencers-nepal', description: 'नेपालभरका गन्तव्यहरू कभर गर्ने ट्राभल क्रिएटरहरू ब्राउज गर्नुहोस्।' },
      ctaHeading: 'चितवनमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'चितवनका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-butwal',
    icon: MapPin,
    keywords: ['influencers Butwal', 'content creators Butwal', 'Butwal influencer marketing', 'hire influencer Butwal'],
    label: { en: 'Butwal creators', ne: 'बुटवल क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Butwal | Hire Butwal Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Butwal on Kolab — a growing commercial hub in Nepal\'s Terai region.',
      breadcrumbName: 'Butwal Influencers',
      eyebrow: 'Influencers in Butwal',
      heading: 'Influencers in Butwal',
      intro: "As a fast-growing commercial hub in Nepal's Terai and the gateway to Lumbini, Butwal is home to a rising creator community covering business, food, and everyday lifestyle content.",
      overviewHeading: "Butwal's creator scene",
      overviewParagraphs: [
        "Butwal's position as a trade and transit hub between the hills and the Terai has fueled steady commercial growth, and local creators increasingly cover retail, food, and lifestyle content for that expanding market.",
        'Kolab helps businesses in Butwal — and brands elsewhere targeting the western Terai — connect with creators based in and around the city.',
      ],
      secondHeading: 'Creators across every niche in Butwal',
      secondParagraphs: [
        'Butwal creators on Kolab post across Food & Beverage, Fashion, and general Lifestyle categories, primarily on Instagram, TikTok, and Facebook.',
        'Businesses can filter for Butwal-based creators specifically when a campaign needs to reach an audience in the western Terai.',
      ],
      trustParagraph: 'Butwal creator partnerships follow the same identity verification and escrow-protected payment process as every location on Kolab.',
      relatedExtra: { label: 'Biratnagar Influencers', path: '/influencers-biratnagar', description: 'Explore creators in another growing commercial hub.' },
      ctaHeading: 'Find Influencers in Butwal',
      ctaSub: 'Download Kolab to connect with Butwal creators.',
    },
    ne: {
      seoTitle: 'Influencers in Butwal | Hire Butwal Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Butwal on Kolab — a growing commercial hub in Nepal\'s Terai region.',
      breadcrumbName: 'बुटवल इन्फ्लुएन्सरहरू',
      eyebrow: 'बुटवलका इन्फ्लुएन्सरहरू',
      heading: 'बुटवलका इन्फ्लुएन्सरहरू',
      intro: 'नेपालको तराईमा छिटो बढिरहेको व्यावसायिक केन्द्र र लुम्बिनीको प्रवेशद्वारको रूपमा, बुटवल व्यवसाय, खाना, र दैनिक लाइफस्टाइल सामग्री समेट्ने उदीयमान क्रिएटर समुदायको घर हो।',
      overviewHeading: 'बुटवलको क्रिएटर दृश्य',
      overviewParagraphs: [
        'पहाड र तराईबीचको व्यापार र ट्रान्जिट केन्द्रको रूपमा बुटवलको स्थितिले निरन्तर व्यावसायिक वृद्धिलाई इन्धन दिएको छ, र स्थानीय क्रिएटरहरूले त्यो विस्तारित बजारका लागि रिटेल, खाना, र लाइफस्टाइल सामग्री बढ्दो रूपमा समेट्दैछन्।',
        'Kolab ले बुटवलका व्यवसायहरू — र पश्चिमी तराईलाई लक्षित गर्ने अन्यत्रका ब्रान्डहरूलाई — सहर र वरपर आधारित क्रिएटरहरूसँग जोड्न मद्दत गर्छ।',
      ],
      secondHeading: 'बुटवलमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा बुटवलका क्रिएटरहरूले मुख्यतः Instagram, TikTok, र Facebook मा खाना र पेय, फेसन, र सामान्य लाइफस्टाइल श्रेणीहरूमा पोस्ट गर्छन्।',
        'क्याम्पेनले पश्चिमी तराईको दर्शकसम्म पुग्नुपर्दा व्यवसायहरूले विशेष गरी बुटवल-आधारित क्रिएटरहरूका लागि फिल्टर गर्न सक्छन्।',
      ],
      trustParagraph: 'बुटवल क्रिएटर साझेदारीहरूले Kolab को हरेक स्थानमा जस्तै उही पहिचान प्रमाणीकरण र एस्क्रो-सुरक्षित भुक्तानी प्रक्रिया पछ्याउँछन्।',
      relatedExtra: { label: 'विराटनगर इन्फ्लुएन्सरहरू', path: '/influencers-biratnagar', description: 'अर्को बढ्दो व्यावसायिक केन्द्रका क्रिएटरहरू अन्वेषण गर्नुहोस्।' },
      ctaHeading: 'बुटवलमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'बुटवलका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-biratnagar',
    icon: MapPin,
    keywords: ['influencers Biratnagar', 'content creators Biratnagar', 'Biratnagar influencer marketing', 'hire influencer Biratnagar'],
    label: { en: 'Biratnagar creators', ne: 'विराटनगर क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Biratnagar | Hire Biratnagar Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Biratnagar on Kolab — eastern Nepal\'s largest commercial and industrial hub.',
      breadcrumbName: 'Biratnagar Influencers',
      eyebrow: 'Influencers in Biratnagar',
      heading: 'Influencers in Biratnagar',
      intro: "As eastern Nepal's largest industrial and commercial city, Biratnagar has a growing creator community serving one of the country's most active regional markets.",
      overviewHeading: "Biratnagar's creator scene",
      overviewParagraphs: [
        'Biratnagar\'s long-standing role as an industrial and trading center has built a substantial local consumer base, and creators here increasingly cover retail, food, and lifestyle content for eastern Nepal\'s businesses.',
        'Kolab connects Biratnagar-based businesses, and brands looking to reach eastern Nepal, with creators who already have a local following in the region.',
      ],
      secondHeading: 'Creators across every niche in Biratnagar',
      secondParagraphs: [
        'Biratnagar creators on Kolab span Food & Beverage, Fashion, and Lifestyle categories, mainly active on Facebook, Instagram, and TikTok.',
        'Brands targeting eastern Nepal specifically can filter creator search for Biratnagar-based profiles.',
      ],
      trustParagraph: 'Biratnagar creator partnerships run through the same verified-creator, escrow-protected process as every location on Kolab.',
      relatedExtra: { label: 'Dharan Influencers', path: '/influencers-dharan', description: 'Explore creators in another eastern Nepal city.' },
      ctaHeading: 'Find Influencers in Biratnagar',
      ctaSub: 'Download Kolab to connect with Biratnagar creators.',
    },
    ne: {
      seoTitle: 'Influencers in Biratnagar | Hire Biratnagar Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Biratnagar on Kolab — eastern Nepal\'s largest commercial and industrial hub.',
      breadcrumbName: 'विराटनगर इन्फ्लुएन्सरहरू',
      eyebrow: 'विराटनगरका इन्फ्लुएन्सरहरू',
      heading: 'विराटनगरका इन्फ्लुएन्सरहरू',
      intro: 'पूर्वी नेपालको सबैभन्दा ठूलो औद्योगिक र व्यावसायिक सहरको रूपमा, विराटनगरमा देशकै सबैभन्दा सक्रिय क्षेत्रीय बजारहरू मध्ये एकलाई सेवा दिने बढ्दो क्रिएटर समुदाय छ।',
      overviewHeading: 'विराटनगरको क्रिएटर दृश्य',
      overviewParagraphs: [
        'औद्योगिक र व्यापार केन्द्रको रूपमा विराटनगरको लामो समयदेखिको भूमिकाले ठूलो स्थानीय उपभोक्ता आधार निर्माण गरेको छ, र यहाँका क्रिएटरहरूले पूर्वी नेपालका व्यवसायहरूका लागि रिटेल, खाना, र लाइफस्टाइल सामग्री बढ्दो रूपमा समेट्दैछन्।',
        'Kolab ले विराटनगर-आधारित व्यवसायहरू, र पूर्वी नेपालसम्म पुग्न चाहने ब्रान्डहरूलाई, क्षेत्रमा पहिले नै स्थानीय फलोइङ भएका क्रिएटरहरूसँग जोड्छ।',
      ],
      secondHeading: 'विराटनगरमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा विराटनगरका क्रिएटरहरूले मुख्यतः Facebook, Instagram, र TikTok मा सक्रिय रहेर खाना र पेय, फेसन, र लाइफस्टाइल श्रेणीहरू समेट्छन्।',
        'विशेष गरी पूर्वी नेपाललाई लक्षित गर्ने ब्रान्डहरूले विराटनगर-आधारित प्रोफाइलका लागि क्रिएटर खोज फिल्टर गर्न सक्छन्।',
      ],
      trustParagraph: 'विराटनगर क्रिएटर साझेदारीहरू Kolab को हरेक स्थानमा जस्तै उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट चल्छन्।',
      relatedExtra: { label: 'धरान इन्फ्लुएन्सरहरू', path: '/influencers-dharan', description: 'पूर्वी नेपालको अर्को सहरका क्रिएटरहरू अन्वेषण गर्नुहोस्।' },
      ctaHeading: 'विराटनगरमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'विराटनगरका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'influencers-dharan',
    icon: MapPin,
    keywords: ['influencers Dharan', 'content creators Dharan', 'Dharan influencer marketing', 'hire influencer Dharan'],
    label: { en: 'Dharan creators', ne: 'धरान क्रिएटरहरू' },
    en: {
      seoTitle: 'Influencers in Dharan | Hire Dharan Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Dharan on Kolab — a fast-growing eastern hill city with an active youth creator scene.',
      breadcrumbName: 'Dharan Influencers',
      eyebrow: 'Influencers in Dharan',
      heading: 'Influencers in Dharan',
      intro: "Known for its clean streets and youthful energy, Dharan has built an active creator community in eastern Nepal covering everyday lifestyle, food, and fashion content.",
      overviewHeading: "Dharan's creator scene",
      overviewParagraphs: [
        "Dharan's reputation as one of Nepal's cleanest and most livable hill cities, combined with a large student and young-professional population, has produced a steady stream of lifestyle, fashion, and food creators.",
        'Kolab connects local businesses in Dharan — and brands targeting eastern Nepal\'s hill region — with creators who post from and about the city.',
      ],
      secondHeading: 'Creators across every niche in Dharan',
      secondParagraphs: [
        'Dharan creators on Kolab cover Fashion, Food & Beverage, and Lifestyle, primarily on Instagram, TikTok, and Facebook.',
        'Businesses can filter for Dharan-based creators to reach the city\'s young, engaged social media audience directly.',
      ],
      trustParagraph: 'Dharan creator partnerships follow the same identity verification and escrow-protected payment process as every location on Kolab.',
      relatedExtra: { label: 'Biratnagar Influencers', path: '/influencers-biratnagar', description: "Explore creators in eastern Nepal's largest commercial hub." },
      ctaHeading: 'Find Influencers in Dharan',
      ctaSub: 'Download Kolab to connect with Dharan creators.',
    },
    ne: {
      seoTitle: 'Influencers in Dharan | Hire Dharan Content Creators',
      seoDescription: 'Find and hire influencers and content creators in Dharan on Kolab — a fast-growing eastern hill city with an active youth creator scene.',
      breadcrumbName: 'धरान इन्फ्लुएन्सरहरू',
      eyebrow: 'धरानका इन्फ्लुएन्सरहरू',
      heading: 'धरानका इन्फ्लुएन्सरहरू',
      intro: 'आफ्ना सफा सडक र युवा ऊर्जाका लागि परिचित, धरानले पूर्वी नेपालमा दैनिक लाइफस्टाइल, खाना, र फेसन सामग्री समेट्ने सक्रिय क्रिएटर समुदाय निर्माण गरेको छ।',
      overviewHeading: 'धरानको क्रिएटर दृश्य',
      overviewParagraphs: [
        'नेपालकै सबैभन्दा सफा र बसोबास योग्य पहाडी सहरहरू मध्ये एकको रूपमा धरानको प्रतिष्ठा, ठूलो विद्यार्थी र युवा-पेशेवर जनसंख्यासँग मिलेर, लाइफस्टाइल, फेसन, र खाना क्रिएटरहरूको निरन्तर प्रवाह उत्पादन गरेको छ।',
        'Kolab ले धरानका स्थानीय व्यवसायहरू — र पूर्वी नेपालको पहाडी क्षेत्रलाई लक्षित गर्ने ब्रान्डहरूलाई — सहरबाट र सहरको बारेमा पोस्ट गर्ने क्रिएटरहरूसँग जोड्छ।',
      ],
      secondHeading: 'धरानमा हरेक निचका क्रिएटरहरू',
      secondParagraphs: [
        'Kolab मा धरानका क्रिएटरहरूले मुख्यतः Instagram, TikTok, र Facebook मा फेसन, खाना र पेय, र लाइफस्टाइल समेट्छन्।',
        'व्यवसायहरूले सहरको युवा, संलग्न सामाजिक सञ्जाल दर्शकसम्म सिधै पुग्न धरान-आधारित क्रिएटरहरूका लागि फिल्टर गर्न सक्छन्।',
      ],
      trustParagraph: 'धरान क्रिएटर साझेदारीहरूले Kolab को हरेक स्थानमा जस्तै उही पहिचान प्रमाणीकरण र एस्क्रो-सुरक्षित भुक्तानी प्रक्रिया पछ्याउँछन्।',
      relatedExtra: { label: 'विराटनगर इन्फ्लुएन्सरहरू', path: '/influencers-biratnagar', description: 'पूर्वी नेपालको सबैभन्दा ठूलो व्यावसायिक केन्द्रका क्रिएटरहरू अन्वेषण गर्नुहोस्।' },
      ctaHeading: 'धरानमा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'धरानका क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
];
