import { MapPin } from 'lucide-react';
import type { NicheConfig } from './NichePage';
import { defaultBenefits, defaultSteps, defaultFaqs, CORE_RELATED } from './shared';

// One entry per "influencers <city>" keyword cluster.
export const CITY_PAGES: NicheConfig[] = [
  {
    slug: 'influencers-kathmandu',
    seoTitle: 'Influencers in Kathmandu | Hire Kathmandu Content Creators',
    seoDescription: "Find and hire influencers and content creators in Kathmandu on Kolab — Nepal's capital and its largest creator community, across every platform and niche.",
    keywords: ['influencers Kathmandu', 'content creators Kathmandu', 'Kathmandu influencer marketing', 'hire influencer Kathmandu'],
    breadcrumbName: 'Kathmandu Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Kathmandu',
    heading: 'Influencers in Kathmandu',
    intro: "As Nepal's capital and largest city, Kathmandu is home to the country's biggest and most active creator community — spanning every platform and niche from fashion to food to tech.",
    overviewHeading: "Kathmandu's creator scene",
    overviewParagraphs: [
      "Kathmandu is where most of Nepal's brands, agencies, and creators are based, which makes it the single largest market on Kolab for finding influencers — whether you need a fashion creator in Thamel, a food reviewer covering New Road's cafes, or a tech creator unboxing the latest phone.",
      'Because so much of Nepal\'s digital economy runs through Kathmandu, brands based here also have the widest pool of creators to choose from across categories, platforms, and follower sizes.',
    ],
    benefits: defaultBenefits('Kathmandu creators'),
    secondHeading: 'Creators across every niche in Kathmandu',
    secondParagraphs: [
      'Kathmandu creators on Kolab cover Food & Beverage, Fashion, Beauty, Technology, Fitness, and nearly every other category, across Instagram, TikTok, YouTube, and Facebook.',
      'Businesses based in Kathmandu — or brands elsewhere looking to reach the capital\'s audience — can filter creator search by location to find people actually based in or covering the city.',
    ],
    steps: defaultSteps('Kathmandu creators'),
    trustParagraph: 'Every creator on Kolab, in Kathmandu or anywhere else in Nepal, goes through the same identity verification and escrow-protected payment process, so scale doesn\'t come at the cost of trust.',
    faqs: defaultFaqs('Kathmandu creators', [
      { question: 'Can I search for creators based specifically in Kathmandu?', answer: 'Yes — creator profiles include location, so you can filter for Kathmandu-based creators alongside category and platform when browsing or posting a campaign.' },
    ]),
    related: [...CORE_RELATED, { label: 'Pokhara Influencers', path: '/influencers-pokhara', description: 'Explore creators based in Pokhara.' }],
    ctaHeading: 'Find Influencers in Kathmandu',
    ctaSub: 'Download Kolab to connect with Kathmandu creators.',
  },
  {
    slug: 'influencers-pokhara',
    seoTitle: 'Influencers in Pokhara | Hire Pokhara Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Pokhara on Kolab — Nepal\'s tourism hub, strong for travel, hospitality, and lifestyle content.',
    keywords: ['influencers Pokhara', 'content creators Pokhara', 'Pokhara influencer marketing', 'hire influencer Pokhara'],
    breadcrumbName: 'Pokhara Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Pokhara',
    heading: 'Influencers in Pokhara',
    intro: "Lakeside cafes, adventure sports, and mountain views make Pokhara Nepal's tourism capital — and its creators are some of the strongest travel and lifestyle content producers in the country.",
    overviewHeading: "Pokhara's creator scene",
    overviewParagraphs: [
      "Pokhara's economy leans heavily on tourism, and its creators reflect that — many post travel vlogs, hotel and cafe reviews, and adventure content (paragliding, boating on Phewa Lake, trekking access points) that performs well with both domestic and international audiences.",
      "Hotels, resorts, travel agencies, and adventure-sports operators in and around Pokhara can find creators on Kolab who already document the city and its surroundings.",
    ],
    benefits: defaultBenefits('Pokhara creators'),
    secondHeading: 'Creators across every niche in Pokhara',
    secondParagraphs: [
      'Beyond travel, Pokhara creators on Kolab also cover Food & Beverage, Lifestyle, and Fitness, giving local businesses outside tourism a way to find relevant creators too.',
      'Brands elsewhere in Nepal can also target Pokhara-based creators for campaigns aimed at the city\'s tourism and hospitality audience.',
    ],
    steps: defaultSteps('Pokhara creators'),
    trustParagraph: 'Pokhara creator partnerships — including hotel stays and adventure-activity collaborations — run through the same verified-creator, escrow-protected process as every location on Kolab.',
    faqs: defaultFaqs('Pokhara creators', [
      { question: 'Is Pokhara good for travel and hospitality campaigns specifically?', answer: 'Yes — Pokhara has one of the strongest concentrations of travel, hotel, and lifestyle creators on Kolab, making it a strong fit for tourism-related campaigns.' },
    ]),
    related: [...CORE_RELATED, { label: 'Travel Influencers', path: '/travel-influencers-nepal', description: 'Browse travel creators covering destinations across Nepal.' }],
    ctaHeading: 'Find Influencers in Pokhara',
    ctaSub: 'Download Kolab to connect with Pokhara creators.',
  },
  {
    slug: 'influencers-lalitpur',
    seoTitle: 'Influencers in Lalitpur | Hire Lalitpur (Patan) Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Lalitpur (Patan) on Kolab — strong for arts, design, and Newari culture content in the Kathmandu Valley.',
    keywords: ['influencers Lalitpur', 'content creators Lalitpur', 'Patan influencers', 'hire influencer Lalitpur'],
    breadcrumbName: 'Lalitpur Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Lalitpur',
    heading: 'Influencers in Lalitpur',
    intro: "Lalitpur (Patan) blends Newari heritage with a modern arts, design, and cafe scene, giving its creators a distinct visual identity within the Kathmandu Valley.",
    overviewHeading: "Lalitpur's creator scene",
    overviewParagraphs: [
      "Home to Patan Durbar Square, artisan workshops, and a growing number of design studios and boutique cafes, Lalitpur has developed a creator community that leans into art, craft, fashion, and aesthetic-driven content.",
      'Kolab connects brands — from local designers to cafes to lifestyle stores — with creators based in Lalitpur who already produce content in that visual register.',
    ],
    benefits: defaultBenefits('Lalitpur creators'),
    secondHeading: 'Creators across every niche in Lalitpur',
    secondParagraphs: [
      'Lalitpur creators on Kolab span Art & Design, Fashion, Food & Beverage, and Lifestyle, alongside general categories, across Instagram and TikTok.',
      'Because Lalitpur sits within the greater Kathmandu Valley, campaigns here often reach much of the same audience as Kathmandu while tapping a distinct creator aesthetic.',
    ],
    steps: defaultSteps('Lalitpur creators'),
    trustParagraph: 'Lalitpur creator collaborations follow the same identity verification and escrow-protected payment process as every location on Kolab.',
    faqs: defaultFaqs('Lalitpur creators'),
    related: [...CORE_RELATED, { label: 'Kathmandu Influencers', path: '/influencers-kathmandu', description: 'Explore creators across the wider Kathmandu Valley.' }],
    ctaHeading: 'Find Influencers in Lalitpur',
    ctaSub: 'Download Kolab to connect with Lalitpur creators.',
  },
  {
    slug: 'influencers-bhaktapur',
    seoTitle: 'Influencers in Bhaktapur | Hire Bhaktapur Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Bhaktapur on Kolab — a UNESCO heritage city strong for culture, craft, and tourism content.',
    keywords: ['influencers Bhaktapur', 'content creators Bhaktapur', 'Bhaktapur influencer marketing', 'hire influencer Bhaktapur'],
    breadcrumbName: 'Bhaktapur Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Bhaktapur',
    heading: 'Influencers in Bhaktapur',
    intro: "Bhaktapur's UNESCO-listed heritage squares and pottery traditions make it one of Nepal's most photographed cities — and a strong base for culture, craft, and tourism-focused creators.",
    overviewHeading: "Bhaktapur's creator scene",
    overviewParagraphs: [
      "Bhaktapur draws heavy domestic and international tourist traffic to its Durbar Square, Pottery Square, and traditional Newari architecture, and its creators often produce heritage, food (like the city's famous juju dhau), and craft content built around that setting.",
      'Kolab connects heritage-tourism operators, craft brands, and local cafes with creators based in Bhaktapur who already cover the city.',
    ],
    benefits: defaultBenefits('Bhaktapur creators'),
    secondHeading: 'Creators across every niche in Bhaktapur',
    secondParagraphs: [
      'Bhaktapur creators on Kolab post under Travel, Food & Beverage, and Art & Design, alongside general lifestyle content, across Instagram and YouTube.',
      'Brands running heritage-tourism or craft-focused campaigns can specifically target Bhaktapur-based creators for authentic, location-grounded content.',
    ],
    steps: defaultSteps('Bhaktapur creators'),
    trustParagraph: 'Bhaktapur creator partnerships run through the same verified-creator, escrow-protected process as every location on Kolab.',
    faqs: defaultFaqs('Bhaktapur creators'),
    related: [...CORE_RELATED, { label: 'Food Influencers', path: '/food-influencers-nepal', description: "Bhaktapur's food and craft content overlaps closely with this category." }],
    ctaHeading: 'Find Influencers in Bhaktapur',
    ctaSub: 'Download Kolab to connect with Bhaktapur creators.',
  },
  {
    slug: 'influencers-chitwan',
    seoTitle: 'Influencers in Chitwan | Hire Chitwan Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Chitwan on Kolab — strong for wildlife tourism, jungle safari, and nature content.',
    keywords: ['influencers Chitwan', 'content creators Chitwan', 'Chitwan influencer marketing', 'hire influencer Chitwan'],
    breadcrumbName: 'Chitwan Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Chitwan',
    heading: 'Influencers in Chitwan',
    intro: "Home to Chitwan National Park, jungle safaris, and a growing resort scene, Chitwan gives brands access to creators who specialize in wildlife tourism and nature content.",
    overviewHeading: "Chitwan's creator scene",
    overviewParagraphs: [
      "Chitwan's identity as Nepal's premier wildlife-tourism destination — rhino sightings, jungle safaris, Tharu cultural shows — has shaped a creator community focused on nature and experiential travel content.",
      'Resorts, safari operators, and eco-tourism brands based in or around Bharatpur and the national park area can connect with Chitwan creators through Kolab.',
    ],
    benefits: defaultBenefits('Chitwan creators'),
    secondHeading: 'Creators across every niche in Chitwan',
    secondParagraphs: [
      'Chitwan creators on Kolab post primarily under Travel, alongside Food & Beverage and Lifestyle, across Instagram and YouTube.',
      'Wildlife lodges and safari operators can offer a free open event — a stay or safari experience in exchange for content — as an alternative to a fixed paid budget.',
    ],
    steps: defaultSteps('Chitwan creators'),
    trustParagraph: 'Stay-for-content and paid campaigns in Chitwan run through the same verified-creator, escrow-protected process as every location on Kolab.',
    faqs: defaultFaqs('Chitwan creators'),
    related: [...CORE_RELATED, { label: 'Travel Influencers', path: '/travel-influencers-nepal', description: 'Browse travel creators covering destinations across Nepal.' }],
    ctaHeading: 'Find Influencers in Chitwan',
    ctaSub: 'Download Kolab to connect with Chitwan creators.',
  },
  {
    slug: 'influencers-butwal',
    seoTitle: 'Influencers in Butwal | Hire Butwal Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Butwal on Kolab — a growing commercial hub in Nepal\'s Terai region.',
    keywords: ['influencers Butwal', 'content creators Butwal', 'Butwal influencer marketing', 'hire influencer Butwal'],
    breadcrumbName: 'Butwal Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Butwal',
    heading: 'Influencers in Butwal',
    intro: "As a fast-growing commercial hub in Nepal's Terai and the gateway to Lumbini, Butwal is home to a rising creator community covering business, food, and everyday lifestyle content.",
    overviewHeading: "Butwal's creator scene",
    overviewParagraphs: [
      "Butwal's position as a trade and transit hub between the hills and the Terai has fueled steady commercial growth, and local creators increasingly cover retail, food, and lifestyle content for that expanding market.",
      'Kolab helps businesses in Butwal — and brands elsewhere targeting the western Terai — connect with creators based in and around the city.',
    ],
    benefits: defaultBenefits('Butwal creators'),
    secondHeading: 'Creators across every niche in Butwal',
    secondParagraphs: [
      'Butwal creators on Kolab post across Food & Beverage, Fashion, and general Lifestyle categories, primarily on Instagram, TikTok, and Facebook.',
      'Businesses can filter for Butwal-based creators specifically when a campaign needs to reach an audience in the western Terai.',
    ],
    steps: defaultSteps('Butwal creators'),
    trustParagraph: 'Butwal creator partnerships follow the same identity verification and escrow-protected payment process as every location on Kolab.',
    faqs: defaultFaqs('Butwal creators'),
    related: [...CORE_RELATED, { label: 'Biratnagar Influencers', path: '/influencers-biratnagar', description: 'Explore creators in another growing commercial hub.' }],
    ctaHeading: 'Find Influencers in Butwal',
    ctaSub: 'Download Kolab to connect with Butwal creators.',
  },
  {
    slug: 'influencers-biratnagar',
    seoTitle: 'Influencers in Biratnagar | Hire Biratnagar Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Biratnagar on Kolab — eastern Nepal\'s largest commercial and industrial hub.',
    keywords: ['influencers Biratnagar', 'content creators Biratnagar', 'Biratnagar influencer marketing', 'hire influencer Biratnagar'],
    breadcrumbName: 'Biratnagar Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Biratnagar',
    heading: 'Influencers in Biratnagar',
    intro: "As eastern Nepal's largest industrial and commercial city, Biratnagar has a growing creator community serving one of the country's most active regional markets.",
    overviewHeading: "Biratnagar's creator scene",
    overviewParagraphs: [
      'Biratnagar\'s long-standing role as an industrial and trading center has built a substantial local consumer base, and creators here increasingly cover retail, food, and lifestyle content for eastern Nepal\'s businesses.',
      'Kolab connects Biratnagar-based businesses, and brands looking to reach eastern Nepal, with creators who already have a local following in the region.',
    ],
    benefits: defaultBenefits('Biratnagar creators'),
    secondHeading: 'Creators across every niche in Biratnagar',
    secondParagraphs: [
      'Biratnagar creators on Kolab span Food & Beverage, Fashion, and Lifestyle categories, mainly active on Facebook, Instagram, and TikTok.',
      'Brands targeting eastern Nepal specifically can filter creator search for Biratnagar-based profiles.',
    ],
    steps: defaultSteps('Biratnagar creators'),
    trustParagraph: 'Biratnagar creator partnerships run through the same verified-creator, escrow-protected process as every location on Kolab.',
    faqs: defaultFaqs('Biratnagar creators'),
    related: [...CORE_RELATED, { label: 'Dharan Influencers', path: '/influencers-dharan', description: 'Explore creators in another eastern Nepal city.' }],
    ctaHeading: 'Find Influencers in Biratnagar',
    ctaSub: 'Download Kolab to connect with Biratnagar creators.',
  },
  {
    slug: 'influencers-dharan',
    seoTitle: 'Influencers in Dharan | Hire Dharan Content Creators',
    seoDescription: 'Find and hire influencers and content creators in Dharan on Kolab — a fast-growing eastern hill city with an active youth creator scene.',
    keywords: ['influencers Dharan', 'content creators Dharan', 'Dharan influencer marketing', 'hire influencer Dharan'],
    breadcrumbName: 'Dharan Influencers',
    icon: MapPin,
    eyebrow: 'Influencers in Dharan',
    heading: 'Influencers in Dharan',
    intro: "Known for its clean streets and youthful energy, Dharan has built an active creator community in eastern Nepal covering everyday lifestyle, food, and fashion content.",
    overviewHeading: "Dharan's creator scene",
    overviewParagraphs: [
      "Dharan's reputation as one of Nepal's cleanest and most livable hill cities, combined with a large student and young-professional population, has produced a steady stream of lifestyle, fashion, and food creators.",
      'Kolab connects local businesses in Dharan — and brands targeting eastern Nepal\'s hill region — with creators who post from and about the city.',
    ],
    benefits: defaultBenefits('Dharan creators'),
    secondHeading: 'Creators across every niche in Dharan',
    secondParagraphs: [
      'Dharan creators on Kolab cover Fashion, Food & Beverage, and Lifestyle, primarily on Instagram, TikTok, and Facebook.',
      'Businesses can filter for Dharan-based creators to reach the city\'s young, engaged social media audience directly.',
    ],
    steps: defaultSteps('Dharan creators'),
    trustParagraph: 'Dharan creator partnerships follow the same identity verification and escrow-protected payment process as every location on Kolab.',
    faqs: defaultFaqs('Dharan creators'),
    related: [...CORE_RELATED, { label: 'Biratnagar Influencers', path: '/influencers-biratnagar', description: "Explore creators in eastern Nepal's largest commercial hub." }],
    ctaHeading: 'Find Influencers in Dharan',
    ctaSub: 'Download Kolab to connect with Dharan creators.',
  },
];
