import {
  Utensils, Plane, Shirt, Sparkles, Dumbbell, Cpu, Wallet, GraduationCap,
  Gamepad2, Car, BedDouble, ChefHat, HeartPulse, Building2,
} from 'lucide-react';
import type { NicheConfig } from './NichePage';
import { defaultBenefits, defaultSteps, defaultFaqs, CORE_RELATED } from './shared';

// One entry per "<industry> influencers Nepal" keyword cluster. Kept as data
// (not one file per page) so the JSX scaffold lives in one place
// (NichePage.tsx) while each entry still gets genuinely distinct copy.
export const INDUSTRY_PAGES: NicheConfig[] = [
  {
    slug: 'food-influencers-nepal',
    seoTitle: 'Food Influencers in Nepal | Hire Food & Restaurant Creators',
    seoDescription: "Find and hire food influencers in Nepal on Kolab — creators covering momo reviews, cafe culture, Newari cuisine, and restaurant promotions in Kathmandu, Pokhara, and beyond.",
    keywords: ['food influencers Nepal', 'restaurant influencers Nepal', 'food creators Nepal', 'hire food influencer Nepal'],
    breadcrumbName: 'Food Influencers',
    icon: Utensils,
    eyebrow: 'Food Influencers Nepal',
    heading: 'Food Influencers in Nepal',
    intro: "From momo reviews to Newari feast pop-ups, Nepal's food scene runs on word of mouth — and increasingly, on short videos. Kolab connects restaurants, cafes, and food brands with creators who already have an audience for exactly that.",
    overviewHeading: 'Why food influencers matter for Nepali restaurants and brands',
    overviewParagraphs: [
      "Kathmandu's cafe culture, Pokhara's lakeside dining scene, and a fast-growing home-delivery market have made food content one of the most watched categories on Nepali social media. A well-shot reel of a new menu item or a honest review of a restaurant can drive foot traffic in a way a paid ad rarely does.",
      'Kolab gives restaurants, cafes, food brands, and beverage companies a direct way to find creators who post food content regularly — instead of guessing who to DM or relying on informal referrals.',
    ],
    benefits: defaultBenefits('food influencers'),
    secondHeading: 'What food creators cover on Kolab',
    secondParagraphs: [
      'Food influencers on Kolab range from street-food reviewers and cafe-hoppers to home-cooking channels and restaurant vloggers, working across Instagram reels, TikTok, and YouTube. Categories like Food & Beverage sit alongside Lifestyle and Entertainment for creators who mix in dining content.',
      'Brands can post a paid campaign for a menu launch, a tasting event, or an ongoing content partnership, or offer a free open event — a tasting invite in exchange for coverage — and let interested creators apply directly.',
    ],
    steps: defaultSteps('food influencers'),
    trustParagraph: 'Restaurant and food brand campaigns on Kolab run through the same verification and escrow protections as every other category — creator identity is checked, and payment for paid tastings or sponsored posts is held securely until the content is approved.',
    faqs: defaultFaqs('food influencers', [
      { question: 'Can I offer a free meal instead of a paid budget?', answer: 'Yes — post a free open event describing what you\'re offering (a tasting, a meal, products) and food creators interested in that kind of collaboration can apply.' },
    ]),
    related: [...CORE_RELATED, { label: 'Instagram Creators', path: '/instagram-creators', description: 'Food content performs especially well on Instagram reels.' }],
    ctaHeading: 'Find Food Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with food creators across Nepal.',
  },
  {
    slug: 'travel-influencers-nepal',
    seoTitle: 'Travel Influencers in Nepal | Hire Travel & Tourism Creators',
    seoDescription: 'Hire travel influencers in Nepal on Kolab — creators covering trekking, homestays, Pokhara, Chitwan, and tourism content for hotels, travel agencies, and destinations.',
    keywords: ['travel influencers Nepal', 'tourism influencers Nepal', 'travel creators Nepal', 'hire travel influencer Nepal'],
    breadcrumbName: 'Travel Influencers',
    icon: Plane,
    eyebrow: 'Travel Influencers Nepal',
    heading: 'Travel Influencers in Nepal',
    intro: "Nepal's tourism economy runs on visuals — trekking routes, lakeside sunsets, jungle safaris, homestays. Kolab connects hotels, travel agencies, and tourism boards with creators who already document travel across the country.",
    overviewHeading: "Why travel content matters for Nepal's tourism industry",
    overviewParagraphs: [
      'Whether it\'s a trek in the Annapurna region, a boat ride on Phewa Lake in Pokhara, or a jungle safari in Chitwan, travel decisions increasingly start with a reel or a vlog, not a brochure. Domestic tourism especially has grown alongside creators who film weekend getaways and hidden local spots.',
      'Kolab helps hotels, resorts, homestays, travel agencies, and destination brands find creators who cover exactly that kind of content, instead of relying on one-off influencer trips arranged informally.',
    ],
    benefits: defaultBenefits('travel influencers'),
    secondHeading: 'What travel creators cover on Kolab',
    secondParagraphs: [
      'Travel creators on Kolab post trekking vlogs, hotel and homestay reviews, road-trip content, and destination guides across YouTube, Instagram, and TikTok, filtered under the Travel category alongside Lifestyle and Photography.',
      'A hotel can post a paid campaign or a free stay-for-content open event; a travel agency can invite creators to document a package tour; a destination brand can run an ongoing seasonal partnership.',
    ],
    steps: defaultSteps('travel influencers'),
    trustParagraph: 'Travel partnerships often involve real trips and stays, which is exactly where informal arrangements go wrong — no clear deliverables, no proof of identity. Kolab keeps creator identity verified and paid-campaign budgets escrow-protected so both sides know what they\'re agreeing to.',
    faqs: defaultFaqs('travel influencers', [
      { question: 'Can I offer a free stay instead of cash payment?', answer: 'Yes — post a free open event describing the stay, trip, or experience you\'re offering, and travel creators interested in that kind of collaboration can apply directly.' },
    ]),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'Longer travel vlogs and destination guides thrive on YouTube.' }],
    ctaHeading: 'Find Travel Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with travel creators across Nepal.',
  },
  {
    slug: 'fashion-influencers-nepal',
    seoTitle: 'Fashion Influencers in Nepal | Hire Fashion & Style Creators',
    seoDescription: 'Hire fashion influencers in Nepal on Kolab — creators covering style, boutique fashion, Dashain-Tihar collections, and outfit content for clothing brands.',
    keywords: ['fashion influencers Nepal', 'fashion creators Nepal', 'style influencers Nepal', 'hire fashion influencer Nepal'],
    breadcrumbName: 'Fashion Influencers',
    icon: Shirt,
    eyebrow: 'Fashion Influencers Nepal',
    heading: 'Fashion Influencers in Nepal',
    intro: "From boutique labels in Kathmandu to festival-season collections for Dashain and Tihar, Nepal's fashion brands rely on creators to turn a new drop into something people actually want to wear. Kolab connects them directly.",
    overviewHeading: 'Why fashion brands in Nepal work with creators',
    overviewParagraphs: [
      "Nepal's fashion market spans everything from local boutique labels and tailoring houses to fast-growing online clothing stores, and outfit content — styling, try-on hauls, festival looks — consistently outperforms static product photos.",
      'Kolab gives clothing brands, boutiques, and designers a way to find fashion creators by aesthetic and platform instead of relying on whoever happens to follow the brand\'s own page.',
    ],
    benefits: defaultBenefits('fashion influencers'),
    secondHeading: 'What fashion creators cover on Kolab',
    secondParagraphs: [
      'Fashion creators on Kolab post styling videos, try-on hauls, festival and wedding-season looks, and brand try-ons across Instagram and TikTok, listed under the Fashion category alongside Beauty and Lifestyle.',
      'A clothing brand can post a paid campaign around a seasonal collection launch, or a free open event offering products in exchange for styled content.',
    ],
    steps: defaultSteps('fashion influencers'),
    trustParagraph: 'Product-based fashion collaborations are verified the same way as paid ones — creator identity is checked, and any paid budget is held in escrow until the agreed content is delivered and approved.',
    faqs: defaultFaqs('fashion influencers'),
    related: [...CORE_RELATED, { label: 'Instagram Creators', path: '/instagram-creators', description: 'Outfit and styling content is built for Instagram reels and carousels.' }],
    ctaHeading: 'Find Fashion Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with fashion creators across Nepal.',
  },
  {
    slug: 'beauty-influencers-nepal',
    seoTitle: 'Beauty Influencers in Nepal | Hire Skincare & Makeup Creators',
    seoDescription: 'Hire beauty influencers in Nepal on Kolab — creators covering skincare routines, makeup tutorials, and salon or cosmetic brand reviews.',
    keywords: ['beauty influencers Nepal', 'beauty creators Nepal', 'makeup influencers Nepal', 'skincare influencers Nepal'],
    breadcrumbName: 'Beauty Influencers',
    icon: Sparkles,
    eyebrow: 'Beauty Influencers Nepal',
    heading: 'Beauty Influencers in Nepal',
    intro: "Skincare routines, makeup tutorials, and honest product reviews drive real purchase decisions in Nepal's growing beauty market. Kolab connects cosmetic brands and salons with the creators shaping those decisions.",
    overviewHeading: "Why beauty content matters in Nepal's cosmetics market",
    overviewParagraphs: [
      'Beauty and skincare brands in Nepal compete in a market where trust matters more than glossy advertising — a creator showing a genuine before-and-after or a real routine carries more weight than a studio ad.',
      'Kolab connects cosmetic brands, skincare lines, and salons with beauty creators who post that kind of content regularly, so a product launch reaches an audience already primed to care.',
    ],
    benefits: defaultBenefits('beauty influencers'),
    secondHeading: 'What beauty creators cover on Kolab',
    secondParagraphs: [
      'Beauty creators on Kolab post skincare routines, makeup tutorials, product reviews, and salon or spa experiences across Instagram, TikTok, and YouTube, listed under the Beauty category alongside Fashion and Lifestyle.',
      'Brands can post a paid review campaign, a product-seeding open event, or an ongoing ambassador-style partnership for a new line.',
    ],
    steps: defaultSteps('beauty influencers'),
    trustParagraph: 'Beauty partnerships on Kolab run through the same identity verification and escrow-protected payments as every category, so product-seeding and paid review campaigns both have a clear, safe process.',
    faqs: defaultFaqs('beauty influencers'),
    related: [...CORE_RELATED, { label: 'TikTok Creators', path: '/tiktok-creators', description: 'Quick tutorials and routines are a strong fit for TikTok.' }],
    ctaHeading: 'Find Beauty Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with beauty creators across Nepal.',
  },
  {
    slug: 'fitness-influencers-nepal',
    seoTitle: 'Fitness Influencers in Nepal | Hire Gym & Wellness Creators',
    seoDescription: 'Hire fitness influencers in Nepal on Kolab — creators covering gym content, home workouts, yoga, and nutrition for fitness brands and gyms.',
    keywords: ['fitness influencers Nepal', 'fitness creators Nepal', 'gym influencers Nepal', 'yoga influencers Nepal'],
    breadcrumbName: 'Fitness Influencers',
    icon: Dumbbell,
    eyebrow: 'Fitness Influencers Nepal',
    heading: 'Fitness Influencers in Nepal',
    intro: "Gym culture, home workouts, and yoga content have built loyal followings across Nepali social media. Kolab connects gyms, supplement brands, and fitness apparel with creators who train and post consistently.",
    overviewHeading: "Why fitness brands in Nepal need creator partnerships",
    overviewParagraphs: [
      "Gyms, sports nutrition brands, and activewear labels in Nepal are competing for attention in a category where demonstrated results matter — a creator's own transformation or workout routine sells harder than a stock photo of dumbbells.",
      'Kolab connects those brands with fitness creators covering strength training, yoga, home workouts, and nutrition, so a gym membership drive or a supplement launch reaches people already following fitness content.',
    ],
    benefits: defaultBenefits('fitness influencers'),
    secondHeading: 'What fitness creators cover on Kolab',
    secondParagraphs: [
      'Fitness creators on Kolab post workout routines, gym reviews, yoga sessions, and nutrition content across Instagram, YouTube, and TikTok, listed under Fitness & Health alongside Sports and Lifestyle.',
      'A gym can post a paid campaign for a membership drive, a supplement brand can run a product-review campaign, or a studio can offer a free open event — class access in exchange for content.',
    ],
    steps: defaultSteps('fitness influencers'),
    trustParagraph: 'Fitness partnerships — including free gym access or product seeding — run through the same verified-creator, escrow-protected process as every category on Kolab.',
    faqs: defaultFaqs('fitness influencers'),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'Full workout routines and nutrition breakdowns suit longer YouTube content.' }],
    ctaHeading: 'Find Fitness Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with fitness creators across Nepal.',
  },
  {
    slug: 'tech-influencers-nepal',
    seoTitle: 'Tech Influencers in Nepal | Hire Technology & Gadget Creators',
    seoDescription: 'Hire tech influencers in Nepal on Kolab — creators covering gadget reviews, app content, and technology news for tech brands and startups.',
    keywords: ['tech influencers Nepal', 'technology influencers Nepal', 'tech creators Nepal', 'gadget reviewers Nepal'],
    breadcrumbName: 'Tech Influencers',
    icon: Cpu,
    eyebrow: 'Tech Influencers Nepal',
    heading: 'Tech Influencers in Nepal',
    intro: "Gadget unboxings, app reviews, and Nepal's growing startup scene all have an audience on YouTube and Instagram. Kolab connects tech brands and startups with the creators covering that space.",
    overviewHeading: "Why tech brands and startups in Nepal need creators",
    overviewParagraphs: [
      "Phone launches, app releases, and local startup announcements move faster on a creator's channel than through a traditional press release — Nepali tech audiences follow reviewers and explainers for buying decisions.",
      'Kolab connects electronics retailers, app developers, and startups with tech creators covering reviews, comparisons, and app walkthroughs, instead of relying on scattered outreach.',
    ],
    benefits: defaultBenefits('tech influencers'),
    secondHeading: 'What tech creators cover on Kolab',
    secondParagraphs: [
      'Tech creators on Kolab post gadget unboxings, phone and laptop reviews, app walkthroughs, and technology explainers across YouTube and Instagram, listed under the Technology category.',
      'A phone retailer can post a paid review campaign, an app can run a launch campaign for install-driving content, or a startup can offer a free open event around a product demo.',
    ],
    steps: defaultSteps('tech influencers'),
    trustParagraph: 'Device loans, early-access app campaigns, and paid review budgets all run through the same verified-creator, escrow-protected process as every category on Kolab.',
    faqs: defaultFaqs('tech influencers'),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'In-depth reviews and comparisons are a natural fit for YouTube.' }],
    ctaHeading: 'Find Tech Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with tech creators across Nepal.',
  },
  {
    slug: 'finance-influencers-nepal',
    seoTitle: 'Finance Influencers in Nepal | Hire Finfluencers & Money Creators',
    seoDescription: 'Hire finance influencers in Nepal on Kolab — creators covering personal finance, digital payments, and investing content for fintech and finance brands.',
    keywords: ['finance influencers Nepal', 'finfluencer Nepal', 'money creators Nepal', 'investing influencers Nepal'],
    breadcrumbName: 'Finance Influencers',
    icon: Wallet,
    eyebrow: 'Finance Influencers Nepal',
    heading: 'Finance Influencers in Nepal',
    intro: "Digital wallets, stock market investing, and personal-finance literacy are growing topics on Nepali social media. Kolab connects fintech companies and finance brands with the creators explaining that world.",
    overviewHeading: 'Why finance brands in Nepal work with creators',
    overviewParagraphs: [
      "As digital payments and retail investing have grown in Nepal, a small but engaged group of creators has built audiences explaining budgeting, saving, and the local stock market (NEPSE) in plain language — a format banks and fintech apps struggle to replicate on their own channels.",
      'Kolab connects fintech apps, banks, and insurance or investment brands with those creators, so a product explainer or a financial-literacy campaign reaches people who are already listening.',
    ],
    benefits: defaultBenefits('finance influencers'),
    secondHeading: 'What finance creators cover on Kolab',
    secondParagraphs: [
      'Finance creators on Kolab post budgeting tips, digital-wallet and app walkthroughs, and investing basics across YouTube and Instagram, listed under the Finance category.',
      'A fintech app can post a paid campaign for an app-explainer series, or a bank can run a financial-literacy content partnership.',
    ],
    steps: defaultSteps('finance influencers'),
    trustParagraph: 'Finance-related campaigns are held to the same verification and escrow standards as every category on Kolab, which matters even more in a category where audience trust is the whole point.',
    faqs: defaultFaqs('finance influencers'),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'Explainer-style finance content performs well as longer YouTube videos.' }],
    ctaHeading: 'Find Finance Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with finance creators across Nepal.',
  },
  {
    slug: 'education-influencers-nepal',
    seoTitle: 'Education Influencers in Nepal | Hire Study & Exam Prep Creators',
    seoDescription: 'Hire education influencers in Nepal on Kolab — creators covering SEE and +2 exam prep, study tips, and study-abroad content for schools and consultancies.',
    keywords: ['education influencers Nepal', 'education creators Nepal', 'study abroad influencers Nepal', 'exam prep influencers Nepal'],
    breadcrumbName: 'Education Influencers',
    icon: GraduationCap,
    eyebrow: 'Education Influencers Nepal',
    heading: 'Education Influencers in Nepal',
    intro: "SEE and +2 exam prep, study-abroad guidance, and coaching-center reviews all have dedicated audiences among Nepali students. Kolab connects schools, consultancies, and edtech brands with creators covering that space.",
    overviewHeading: 'Why education brands in Nepal need creators',
    overviewParagraphs: [
      "Study-abroad consultancies, coaching centers, and edtech apps compete for the attention of students who increasingly research decisions — which country, which consultancy, which exam strategy — through creator content rather than brochures alone.",
      'Kolab connects those brands with education creators posting exam tips, study-abroad journeys, and coaching reviews, so a consultancy or coaching center reaches students already engaging with that content.',
    ],
    benefits: defaultBenefits('education influencers'),
    secondHeading: 'What education creators cover on Kolab',
    secondParagraphs: [
      'Education creators on Kolab post exam prep tips, study-abroad vlogs, coaching and course reviews, and study-technique content across YouTube and Instagram, listed under the Education category.',
      'A consultancy can post a paid campaign around an admissions season, or a coaching center can offer a free open event — course access in exchange for a review series.',
    ],
    steps: defaultSteps('education influencers'),
    trustParagraph: 'Education campaigns follow the same verified-creator, escrow-protected process as every category, which matters given how much students rely on this content for high-stakes decisions.',
    faqs: defaultFaqs('education influencers'),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'Long-form exam prep and study-abroad guides suit YouTube well.' }],
    ctaHeading: 'Find Education Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with education creators across Nepal.',
  },
  {
    slug: 'gaming-influencers-nepal',
    seoTitle: 'Gaming Influencers in Nepal | Hire Esports & Mobile Gaming Creators',
    seoDescription: 'Hire gaming influencers in Nepal on Kolab — creators covering mobile esports, game streaming, and gaming-gear reviews for gaming and tech brands.',
    keywords: ['gaming influencers Nepal', 'gaming creators Nepal', 'esports influencers Nepal', 'streamers Nepal'],
    breadcrumbName: 'Gaming Influencers',
    icon: Gamepad2,
    eyebrow: 'Gaming Influencers Nepal',
    heading: 'Gaming Influencers in Nepal',
    intro: "Mobile esports and streaming have built a large, engaged gaming audience in Nepal. Kolab connects gaming brands, cyber cafes, and tech companies with the creators and streamers driving that scene.",
    overviewHeading: "Why gaming brands in Nepal work with creators",
    overviewParagraphs: [
      "Mobile titles have turned casual play into a competitive, watched scene in Nepal, with streamers and tournament players building sizable followings on YouTube, Facebook, and TikTok.",
      'Kolab connects gaming-gear brands, mobile game publishers, and cyber cafes or gaming lounges with gaming creators, so a product launch or a tournament sponsorship reaches an audience that\'s already watching.',
    ],
    benefits: defaultBenefits('gaming influencers'),
    secondHeading: 'What gaming creators cover on Kolab',
    secondParagraphs: [
      'Gaming creators on Kolab stream and post gameplay, gear reviews, and tournament content across YouTube, Facebook, and TikTok, listed under the Gaming category.',
      'A gaming-gear brand can post a paid review campaign, or a mobile game publisher can run a launch campaign built around creator gameplay content.',
    ],
    steps: defaultSteps('gaming influencers'),
    trustParagraph: 'Gear sponsorships, paid streams, and tournament partnerships all run through the same verified-creator, escrow-protected process as every category on Kolab.',
    faqs: defaultFaqs('gaming influencers'),
    related: [...CORE_RELATED, { label: 'Facebook Creators', path: '/facebook-creators', description: 'Live gameplay and gaming clips have a strong following on Facebook in Nepal.' }],
    ctaHeading: 'Find Gaming Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with gaming creators across Nepal.',
  },
  {
    slug: 'automobile-influencers-nepal',
    seoTitle: 'Automobile Influencers in Nepal | Hire Car & Bike Review Creators',
    seoDescription: 'Hire automobile influencers in Nepal on Kolab — creators covering bike and car reviews, test rides, and auto-brand content.',
    keywords: ['automobile influencers Nepal', 'auto influencers Nepal', 'bike review creators Nepal', 'car influencers Nepal'],
    breadcrumbName: 'Automobile Influencers',
    icon: Car,
    eyebrow: 'Automobile Influencers Nepal',
    heading: 'Automobile Influencers in Nepal',
    intro: "Bike and car reviews, test rides, and comparison videos have a dedicated audience among Nepali buyers weighing a big purchase. Kolab connects dealerships and auto brands with the creators they trust.",
    overviewHeading: 'Why auto brands in Nepal need creator reviews',
    overviewParagraphs: [
      "Vehicles are a major purchase in Nepal, and buyers increasingly research bikes and cars through independent review creators before visiting a showroom — mileage, road performance, and honest pros and cons carry more weight than a brochure spec sheet.",
      'Kolab connects dealerships, auto brands, and accessory shops with creators who cover test rides and comparisons, so a new launch reaches buyers already in research mode.',
    ],
    benefits: defaultBenefits('automobile influencers'),
    secondHeading: 'What automobile creators cover on Kolab',
    secondParagraphs: [
      'Automobile creators on Kolab post test-ride reviews, comparison videos, and road-trip content across YouTube and Facebook, most closely matched under the Technology and Lifestyle categories.',
      'A dealership can post a paid campaign around a new model launch, or offer a free open event — a test ride in exchange for a review video.',
    ],
    steps: defaultSteps('automobile influencers'),
    trustParagraph: 'Test-ride loans and paid review campaigns run through the same verified-creator, escrow-protected process as every category on Kolab.',
    faqs: defaultFaqs('automobile influencers'),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'Detailed test-ride and comparison reviews suit longer YouTube videos.' }],
    ctaHeading: 'Find Automobile Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with automobile creators across Nepal.',
  },
  {
    slug: 'hotel-influencers-nepal',
    seoTitle: 'Hotel Influencers in Nepal | Hire Hospitality & Stay Creators',
    seoDescription: 'Hire hotel influencers in Nepal on Kolab — creators covering hotel and resort stays, hospitality reviews, and destination content.',
    keywords: ['hotel influencers Nepal', 'hospitality influencers Nepal', 'hotel creators Nepal', 'resort influencers Nepal'],
    breadcrumbName: 'Hotel Influencers',
    icon: BedDouble,
    eyebrow: 'Hotel Influencers Nepal',
    heading: 'Hotel Influencers in Nepal',
    intro: "A hotel stay documented well is one of the strongest booking drivers in tourism. Kolab connects hotels and resorts across Nepal with creators who cover stays, amenities, and guest experiences.",
    overviewHeading: 'Why hotels in Nepal work with creators',
    overviewParagraphs: [
      'Hotel and resort bookings increasingly follow a creator\'s room tour or stay vlog rather than a listing photo alone — guests want to see the actual room, the view, the breakfast, before booking.',
      'Kolab connects hotels, resorts, and boutique stays across Nepal with creators who produce that kind of stay content, whether it\'s a Pokhara lakeside resort or a Kathmandu boutique hotel.',
    ],
    benefits: defaultBenefits('hotel influencers'),
    secondHeading: 'What hotel and hospitality creators cover on Kolab',
    secondParagraphs: [
      'Hospitality creators on Kolab post stay vlogs, room tours, and amenity reviews across Instagram and YouTube, closely matched under the Travel category.',
      'A hotel can post a free open event — a complimentary stay in exchange for content — or a paid campaign for an ongoing content partnership around a new property or season.',
    ],
    steps: defaultSteps('hotel influencers'),
    trustParagraph: 'Complimentary-stay collaborations and paid campaigns both go through Kolab\'s verified-creator and escrow-protected process, so hotels know who they\'re hosting and creators know they\'ll be paid as agreed.',
    faqs: defaultFaqs('hotel influencers'),
    related: [...CORE_RELATED, { label: 'Travel Influencers', path: '/travel-influencers-nepal', description: 'Hotel stays are a core part of travel content on Kolab.' }],
    ctaHeading: 'Find Hotel Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with hospitality creators across Nepal.',
  },
  {
    slug: 'restaurant-influencers-nepal',
    seoTitle: 'Restaurant Influencers in Nepal | Hire Cafe & Dining Creators',
    seoDescription: 'Hire restaurant influencers in Nepal on Kolab — creators covering restaurant reviews, cafe visits, and menu launches for dining brands.',
    keywords: ['restaurant influencers Nepal', 'restaurant creators Nepal', 'cafe influencers Nepal', 'dining influencers Nepal'],
    breadcrumbName: 'Restaurant Influencers',
    icon: ChefHat,
    eyebrow: 'Restaurant Influencers Nepal',
    heading: 'Restaurant Influencers in Nepal',
    intro: "A new restaurant or cafe in Kathmandu, Pokhara, or Lalitpur lives or dies on the first wave of reviews and recommendations. Kolab connects dining brands with the creators who shape that first impression.",
    overviewHeading: 'Why restaurants in Nepal work with creators',
    overviewParagraphs: [
      "With cafe culture booming across Nepal's cities, restaurant openings and menu launches increasingly rely on creator visits and reviews to build early buzz rather than traditional advertising alone.",
      'Kolab helps restaurants, cafes, and dining brands find creators who post that kind of review and visit content consistently, matched to their location and cuisine.',
    ],
    benefits: defaultBenefits('restaurant influencers'),
    secondHeading: 'What restaurant creators cover on Kolab',
    secondParagraphs: [
      'Restaurant and cafe creators on Kolab post visit vlogs, menu reviews, and ambience content across Instagram reels and TikTok, listed under Food & Beverage.',
      'A restaurant can post a free open event — a complimentary meal in exchange for coverage — or a paid campaign for a launch or ongoing content partnership.',
    ],
    steps: defaultSteps('restaurant influencers'),
    trustParagraph: 'Complimentary-meal collaborations and paid campaigns both run through Kolab\'s verified-creator and escrow-protected process, keeping restaurant partnerships straightforward and accountable.',
    faqs: defaultFaqs('restaurant influencers'),
    related: [...CORE_RELATED, { label: 'Food Influencers', path: '/food-influencers-nepal', description: 'Restaurant and food content overlap closely on Kolab.' }],
    ctaHeading: 'Find Restaurant Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with restaurant creators across Nepal.',
  },
  {
    slug: 'healthcare-influencers-nepal',
    seoTitle: 'Healthcare Influencers in Nepal | Hire Wellness & Health Creators',
    seoDescription: 'Hire healthcare influencers in Nepal on Kolab — creators covering wellness, mental health awareness, and clinic or health-brand content.',
    keywords: ['healthcare influencers Nepal', 'health influencers Nepal', 'wellness creators Nepal', 'health creators Nepal'],
    breadcrumbName: 'Healthcare Influencers',
    icon: HeartPulse,
    eyebrow: 'Healthcare Influencers Nepal',
    heading: 'Healthcare Influencers in Nepal',
    intro: "Wellness and mental-health awareness content has grown steadily on Nepali social media. Kolab connects clinics, health brands, and wellness businesses with creators covering that space responsibly.",
    overviewHeading: 'Why health and wellness brands in Nepal work with creators',
    overviewParagraphs: [
      'As conversations around mental health, general wellness, and preventive care have opened up in Nepal, a growing group of creators has built audiences around approachable, non-clinical health content — a tone traditional healthcare advertising often misses.',
      'Kolab connects clinics, wellness centers, and health-product brands with those creators, so a wellness campaign reaches an audience that already engages with the topic.',
    ],
    benefits: defaultBenefits('healthcare influencers'),
    secondHeading: 'What healthcare and wellness creators cover on Kolab',
    secondParagraphs: [
      'Wellness creators on Kolab post general health tips, mental-health awareness content, and product or service reviews across Instagram and YouTube, most closely matched under Fitness & Health and Lifestyle.',
      'A clinic or wellness brand can post a paid awareness campaign, or offer a free open event around a service trial in exchange for honest coverage.',
    ],
    steps: defaultSteps('healthcare influencers'),
    trustParagraph: 'Health-related content carries extra responsibility, and Kolab\'s creator verification and escrow-protected payments apply the same way here as in every category — identity checked, budgets held until approved work is delivered.',
    faqs: defaultFaqs('healthcare influencers'),
    related: [...CORE_RELATED, { label: 'Fitness Influencers', path: '/fitness-influencers-nepal', description: 'Wellness and fitness content overlap closely on Kolab.' }],
    ctaHeading: 'Find Healthcare Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with wellness creators across Nepal.',
  },
  {
    slug: 'real-estate-influencers-nepal',
    seoTitle: 'Real Estate Influencers in Nepal | Hire Property Content Creators',
    seoDescription: 'Hire real estate influencers in Nepal on Kolab — creators covering property tours, apartment reviews, and real-estate content in Kathmandu Valley and beyond.',
    keywords: ['real estate influencers Nepal', 'property influencers Nepal', 'real estate creators Nepal', 'property content creators Nepal'],
    breadcrumbName: 'Real Estate Influencers',
    icon: Building2,
    eyebrow: 'Real Estate Influencers Nepal',
    heading: 'Real Estate Influencers in Nepal',
    intro: "Apartment tours and property walkthroughs help buyers and renters make decisions long before a site visit. Kolab connects real estate developers and agents with creators who produce that content.",
    overviewHeading: 'Why real estate brands in Nepal work with creators',
    overviewParagraphs: [
      "As apartment and housing developments have expanded across the Kathmandu Valley and other growing cities, buyers and renters increasingly want a video walkthrough before committing to a site visit — something static listing photos can't provide.",
      'Kolab connects developers, real estate agents, and property brands with creators who produce property tours and area guides, so a new listing or project reaches serious, research-stage buyers.',
    ],
    benefits: defaultBenefits('real estate influencers'),
    secondHeading: 'What real estate creators cover on Kolab',
    secondParagraphs: [
      'Real estate creators on Kolab post property walkthroughs, apartment reviews, and neighborhood guides across YouTube and Instagram, most closely matched under the Home & Living category.',
      'A developer can post a paid campaign for a project launch, or a real estate agency can run an ongoing content partnership covering multiple listings.',
    ],
    steps: defaultSteps('real estate influencers'),
    trustParagraph: 'Property-tour campaigns run through the same verified-creator, escrow-protected process as every category on Kolab, which matters for a category involving high-value listings and site access.',
    faqs: defaultFaqs('real estate influencers'),
    related: [...CORE_RELATED, { label: 'YouTube Creators', path: '/youtube-creators', description: 'Full property walkthroughs suit longer YouTube videos.' }],
    ctaHeading: 'Find Real Estate Influencers in Nepal',
    ctaSub: 'Download Kolab to connect with real estate creators across Nepal.',
  },
];
