import {
  Utensils, Plane, Shirt, Sparkles, Dumbbell, Cpu, Wallet, GraduationCap,
  Gamepad2, Car, BedDouble, ChefHat, HeartPulse, Building2,
} from 'lucide-react';
import type { NicheConfig } from './NichePage';

// One entry per "<industry> influencers Nepal" keyword cluster. Kept as data
// (not one file per page) so the JSX scaffold lives in one place
// (NichePage.tsx) while each entry still gets genuinely distinct copy.
// Bilingual: `label` is the short niche label plugged into shared.ts's
// templated benefits/steps/FAQs, and `en`/`ne` hold the page-specific copy
// (SEO meta is left identical between languages — only visible content is
// translated).
export const INDUSTRY_PAGES: NicheConfig[] = [
  {
    slug: 'food-influencers-nepal',
    icon: Utensils,
    keywords: ['food influencers Nepal', 'restaurant influencers Nepal', 'food creators Nepal', 'hire food influencer Nepal'],
    label: { en: 'food influencers', ne: 'खाना इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Food Influencers in Nepal | Hire Food & Restaurant Creators',
      seoDescription: "Find and hire food influencers in Nepal on Kolab — creators covering momo reviews, cafe culture, Newari cuisine, and restaurant promotions in Kathmandu, Pokhara, and beyond.",
      breadcrumbName: 'Food Influencers',
      eyebrow: 'Food Influencers Nepal',
      heading: 'Food Influencers in Nepal',
      intro: "From momo reviews to Newari feast pop-ups, Nepal's food scene runs on word of mouth — and increasingly, on short videos. Kolab connects restaurants, cafes, and food brands with creators who already have an audience for exactly that.",
      overviewHeading: 'Why food influencers matter for Nepali restaurants and brands',
      overviewParagraphs: [
        "Kathmandu's cafe culture, Pokhara's lakeside dining scene, and a fast-growing home-delivery market have made food content one of the most watched categories on Nepali social media. A well-shot reel of a new menu item or a honest review of a restaurant can drive foot traffic in a way a paid ad rarely does.",
        'Kolab gives restaurants, cafes, food brands, and beverage companies a direct way to find creators who post food content regularly — instead of guessing who to DM or relying on informal referrals.',
      ],
      secondHeading: 'What food creators cover on Kolab',
      secondParagraphs: [
        'Food influencers on Kolab range from street-food reviewers and cafe-hoppers to home-cooking channels and restaurant vloggers, working across Instagram reels, TikTok, and YouTube. Categories like Food & Beverage sit alongside Lifestyle and Entertainment for creators who mix in dining content.',
        'Brands can post a paid campaign for a menu launch, a tasting event, or an ongoing content partnership, or offer a free open event — a tasting invite in exchange for coverage — and let interested creators apply directly.',
      ],
      trustParagraph: 'Restaurant and food brand campaigns on Kolab run through the same verification and escrow protections as every other category — creator identity is checked, and payment for paid tastings or sponsored posts is held securely until the content is approved.',
      faqsExtra: [
        { question: 'Can I offer a free meal instead of a paid budget?', answer: 'Yes — post a free open event describing what you\'re offering (a tasting, a meal, products) and food creators interested in that kind of collaboration can apply.' },
      ],
      relatedExtra: { label: 'Instagram Creators', path: '/instagram-creators', description: 'Food content performs especially well on Instagram reels.' },
      ctaHeading: 'Find Food Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with food creators across Nepal.',
    },
    ne: {
      seoTitle: 'Food Influencers in Nepal | Hire Food & Restaurant Creators',
      seoDescription: "Find and hire food influencers in Nepal on Kolab — creators covering momo reviews, cafe culture, Newari cuisine, and restaurant promotions in Kathmandu, Pokhara, and beyond.",
      breadcrumbName: 'खाना इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका खाना इन्फ्लुएन्सरहरू',
      heading: 'नेपालका खाना इन्फ्लुएन्सरहरू',
      intro: 'मोमो समीक्षादेखि नेवारी भोज पप-अपसम्म, नेपालको खाना दृश्य मुखबाट-मुख प्रचारमा चल्छ — र बढ्दो रूपमा छोटा भिडियोहरूमा। Kolab ले रेस्टुरेन्ट, क्याफे, र खाना ब्रान्डहरूलाई त्यस्तै दर्शक भइसकेका क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपाली रेस्टुरेन्ट र ब्रान्डहरूका लागि खाना इन्फ्लुएन्सरहरू किन महत्त्वपूर्ण छन्',
      overviewParagraphs: [
        'काठमाडौंको क्याफे संस्कृति, पोखराको ताल किनारको डाइनिङ दृश्य, र छिटो बढिरहेको घर-डेलिभरी बजारले खाना सामग्रीलाई नेपाली सामाजिक सञ्जालमा सबैभन्दा हेरिने श्रेणीहरूमध्ये एक बनाएको छ। नयाँ मेनु आइटमको राम्रोसँग खिचिएको रिल वा रेस्टुरेन्टको इमानदार समीक्षाले भुक्तानी गरिएको विज्ञापनले भन्दा फरक तरिकाले पैदल ग्राहक ल्याउन सक्छ।',
        'Kolab ले रेस्टुरेन्ट, क्याफे, खाना ब्रान्ड, र पेय कम्पनीहरूलाई नियमित रूपमा खाना सामग्री पोस्ट गर्ने क्रिएटरहरू फेला पार्ने सिधा तरिका दिन्छ — कसलाई DM गर्ने भनेर अनुमान लगाउनु वा अनौपचारिक सिफारिसमा भर पर्नुको सट्टा।',
      ],
      secondHeading: 'Kolab मा खाना क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab मा खाना इन्फ्लुएन्सरहरू सडक-खाना समीक्षकदेखि क्याफे-होपर र घर-खाना च्यानलदेखि रेस्टुरेन्ट भ्लगरसम्म फैलिएका छन्, जसले Instagram रिल, TikTok, र YouTube मा काम गर्छन्। खाना र पेय जस्ता श्रेणीहरू लाइफस्टाइल र मनोरञ्जनसँगै डाइनिङ सामग्री मिसाउने क्रिएटरहरूका लागि उपलब्ध छन्।',
        'ब्रान्डहरूले मेनु सुरुवात, स्वाद परीक्षण कार्यक्रम, वा निरन्तर सामग्री साझेदारीका लागि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छन्, वा निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छन् — कभरेजको बदलामा स्वाद परीक्षण निम्तो — र इच्छुक क्रिएटरहरूलाई सिधै आवेदन दिन दिन सक्छन्।',
      ],
      trustParagraph: 'Kolab मा रेस्टुरेन्ट र खाना ब्रान्ड क्याम्पेनहरू अन्य सबै श्रेणी जस्तै उही प्रमाणीकरण र एस्क्रो सुरक्षाबाट गुज्र्छन् — क्रिएटरको पहिचान जाँचिन्छ, र भुक्तानी हुने स्वाद परीक्षण वा प्रायोजित पोस्टको भुक्तानी सामग्री स्वीकृत नभएसम्म सुरक्षित रूपमा राखिन्छ।',
      faqsExtra: [
        { question: 'के म तलबसहितको बजेटको सट्टा निःशुल्क खाना प्रस्ताव गर्न सक्छु?', answer: 'हो — तपाईंले प्रस्ताव गरिरहनुभएको कुरा (स्वाद परीक्षण, खाना, प्रोडक्ट) वर्णन गर्दै निःशुल्क खुला इभेन्ट पोस्ट गर्नुहोस्, र त्यस्तो सहकार्यमा रुचि राख्ने खाना क्रिएटरहरूले आवेदन दिन सक्छन्।' },
      ],
      relatedExtra: { label: 'Instagram क्रिएटरहरू', path: '/instagram-creators', description: 'खाना सामग्रीले Instagram रिलमा विशेष गरी राम्रो प्रदर्शन गर्छ।' },
      ctaHeading: 'नेपालमा खाना इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका खाना क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'travel-influencers-nepal',
    icon: Plane,
    keywords: ['travel influencers Nepal', 'tourism influencers Nepal', 'travel creators Nepal', 'hire travel influencer Nepal'],
    label: { en: 'travel influencers', ne: 'ट्राभल इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Travel Influencers in Nepal | Hire Travel & Tourism Creators',
      seoDescription: 'Hire travel influencers in Nepal on Kolab — creators covering trekking, homestays, Pokhara, Chitwan, and tourism content for hotels, travel agencies, and destinations.',
      breadcrumbName: 'Travel Influencers',
      eyebrow: 'Travel Influencers Nepal',
      heading: 'Travel Influencers in Nepal',
      intro: "Nepal's tourism economy runs on visuals — trekking routes, lakeside sunsets, jungle safaris, homestays. Kolab connects hotels, travel agencies, and tourism boards with creators who already document travel across the country.",
      overviewHeading: "Why travel content matters for Nepal's tourism industry",
      overviewParagraphs: [
        'Whether it\'s a trek in the Annapurna region, a boat ride on Phewa Lake in Pokhara, or a jungle safari in Chitwan, travel decisions increasingly start with a reel or a vlog, not a brochure. Domestic tourism especially has grown alongside creators who film weekend getaways and hidden local spots.',
        'Kolab helps hotels, resorts, homestays, travel agencies, and destination brands find creators who cover exactly that kind of content, instead of relying on one-off influencer trips arranged informally.',
      ],
      secondHeading: 'What travel creators cover on Kolab',
      secondParagraphs: [
        'Travel creators on Kolab post trekking vlogs, hotel and homestay reviews, road-trip content, and destination guides across YouTube, Instagram, and TikTok, filtered under the Travel category alongside Lifestyle and Photography.',
        'A hotel can post a paid campaign or a free stay-for-content open event; a travel agency can invite creators to document a package tour; a destination brand can run an ongoing seasonal partnership.',
      ],
      trustParagraph: 'Travel partnerships often involve real trips and stays, which is exactly where informal arrangements go wrong — no clear deliverables, no proof of identity. Kolab keeps creator identity verified and paid-campaign budgets escrow-protected so both sides know what they\'re agreeing to.',
      faqsExtra: [
        { question: 'Can I offer a free stay instead of cash payment?', answer: 'Yes — post a free open event describing the stay, trip, or experience you\'re offering, and travel creators interested in that kind of collaboration can apply directly.' },
      ],
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'Longer travel vlogs and destination guides thrive on YouTube.' },
      ctaHeading: 'Find Travel Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with travel creators across Nepal.',
    },
    ne: {
      seoTitle: 'Travel Influencers in Nepal | Hire Travel & Tourism Creators',
      seoDescription: 'Hire travel influencers in Nepal on Kolab — creators covering trekking, homestays, Pokhara, Chitwan, and tourism content for hotels, travel agencies, and destinations.',
      breadcrumbName: 'ट्राभल इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका ट्राभल इन्फ्लुएन्सरहरू',
      heading: 'नेपालका ट्राभल इन्फ्लुएन्सरहरू',
      intro: 'नेपालको पर्यटन अर्थतन्त्र दृश्यहरूमा चल्छ — ट्रेकिङ मार्ग, ताल किनारका सूर्यास्त, जंगल सफारी, होमस्टे। Kolab ले होटल, ट्राभल एजेन्सी, र पर्यटन बोर्डहरूलाई देशभरि यात्रा कागजात गरिरहेका क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालको पर्यटन उद्योगका लागि ट्राभल सामग्री किन महत्त्वपूर्ण छ',
      overviewParagraphs: [
        'अन्नपूर्ण क्षेत्रमा ट्रेक होस्, पोखराको फेवा तालमा डुंगा सवारी होस्, वा चितवनमा जंगल सफारी होस्, यात्रा सम्बन्धी निर्णयहरू बढ्दो रूपमा ब्रोसरबाट होइन, रिल वा भ्लगबाट सुरु हुन्छन्। विशेष गरी आन्तरिक पर्यटन साप्ताहिक बिदाका यात्रा र लुकेका स्थानीय ठाउँहरू फिल्माउने क्रिएटरहरूसँगै बढेको छ।',
        'Kolab ले होटल, रिसोर्ट, होमस्टे, ट्राभल एजेन्सी, र गन्तव्य ब्रान्डहरूलाई त्यस्तै सामग्री समेट्ने क्रिएटरहरू फेला पार्न मद्दत गर्छ, अनौपचारिक रूपमा मिलाइएका एक-पटके इन्फ्लुएन्सर यात्रामा भर पर्नुको सट्टा।',
      ],
      secondHeading: 'Kolab मा ट्राभल क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का ट्राभल क्रिएटरहरूले YouTube, Instagram, र TikTok मा ट्रेकिङ भ्लग, होटल र होमस्टे समीक्षा, रोड-ट्रिप सामग्री, र गन्तव्य गाइडहरू पोस्ट गर्छन्, जुन लाइफस्टाइल र फोटोग्राफीसँगै ट्राभल श्रेणीअन्तर्गत फिल्टर गरिन्छन्।',
        'होटलले तलबसहितको क्याम्पेन वा सामग्रीको बदलामा निःशुल्क बसाइको खुला इभेन्ट पोस्ट गर्न सक्छ; ट्राभल एजेन्सीले प्याकेज टुर कागजात गर्न क्रिएटरहरूलाई आमन्त्रित गर्न सक्छ; गन्तव्य ब्रान्डले निरन्तर सिजनल साझेदारी चलाउन सक्छ।',
      ],
      trustParagraph: 'ट्राभल साझेदारीमा प्रायः वास्तविक यात्रा र बसाइ समावेश हुन्छ, जुन ठ्याक्कै त्यही ठाउँ हो जहाँ अनौपचारिक व्यवस्थाहरू बिग्रन्छन् — स्पष्ट डेलिभरेबल छैन, पहिचानको प्रमाण छैन। Kolab ले क्रिएटरको पहिचान प्रमाणित राख्छ र तलबसहितको क्याम्पेन बजेट एस्क्रो-सुरक्षित राख्छ ताकि दुवै पक्षलाई थाहा होस् उनीहरू केमा सहमत भइरहेका छन्।',
      faqsExtra: [
        { question: 'के म नगद भुक्तानीको सट्टा निःशुल्क बसाइ प्रस्ताव गर्न सक्छु?', answer: 'हो — तपाईंले प्रस्ताव गरिरहनुभएको बसाइ, यात्रा, वा अनुभव वर्णन गर्दै निःशुल्क खुला इभेन्ट पोस्ट गर्नुहोस्, र त्यस्तो सहकार्यमा रुचि राख्ने ट्राभल क्रिएटरहरूले सिधै आवेदन दिन सक्छन्।' },
      ],
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'लामो ट्राभल भ्लग र गन्तव्य गाइडहरू YouTube मा राम्रोसँग फस्टाउँछन्।' },
      ctaHeading: 'नेपालमा ट्राभल इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका ट्राभल क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'fashion-influencers-nepal',
    icon: Shirt,
    keywords: ['fashion influencers Nepal', 'fashion creators Nepal', 'style influencers Nepal', 'hire fashion influencer Nepal'],
    label: { en: 'fashion influencers', ne: 'फेसन इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Fashion Influencers in Nepal | Hire Fashion & Style Creators',
      seoDescription: 'Hire fashion influencers in Nepal on Kolab — creators covering style, boutique fashion, Dashain-Tihar collections, and outfit content for clothing brands.',
      breadcrumbName: 'Fashion Influencers',
      eyebrow: 'Fashion Influencers Nepal',
      heading: 'Fashion Influencers in Nepal',
      intro: "From boutique labels in Kathmandu to festival-season collections for Dashain and Tihar, Nepal's fashion brands rely on creators to turn a new drop into something people actually want to wear. Kolab connects them directly.",
      overviewHeading: 'Why fashion brands in Nepal work with creators',
      overviewParagraphs: [
        "Nepal's fashion market spans everything from local boutique labels and tailoring houses to fast-growing online clothing stores, and outfit content — styling, try-on hauls, festival looks — consistently outperforms static product photos.",
        'Kolab gives clothing brands, boutiques, and designers a way to find fashion creators by aesthetic and platform instead of relying on whoever happens to follow the brand\'s own page.',
      ],
      secondHeading: 'What fashion creators cover on Kolab',
      secondParagraphs: [
        'Fashion creators on Kolab post styling videos, try-on hauls, festival and wedding-season looks, and brand try-ons across Instagram and TikTok, listed under the Fashion category alongside Beauty and Lifestyle.',
        'A clothing brand can post a paid campaign around a seasonal collection launch, or a free open event offering products in exchange for styled content.',
      ],
      trustParagraph: 'Product-based fashion collaborations are verified the same way as paid ones — creator identity is checked, and any paid budget is held in escrow until the agreed content is delivered and approved.',
      relatedExtra: { label: 'Instagram Creators', path: '/instagram-creators', description: 'Outfit and styling content is built for Instagram reels and carousels.' },
      ctaHeading: 'Find Fashion Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with fashion creators across Nepal.',
    },
    ne: {
      seoTitle: 'Fashion Influencers in Nepal | Hire Fashion & Style Creators',
      seoDescription: 'Hire fashion influencers in Nepal on Kolab — creators covering style, boutique fashion, Dashain-Tihar collections, and outfit content for clothing brands.',
      breadcrumbName: 'फेसन इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका फेसन इन्फ्लुएन्सरहरू',
      heading: 'नेपालका फेसन इन्फ्लुएन्सरहरू',
      intro: 'काठमाडौंका बुटिक लेबलदेखि दशैं-तिहारका पर्व-सिजन कलेक्सनसम्म, नेपालका फेसन ब्रान्डहरूले नयाँ ड्रपलाई मानिसहरूले साँच्चै लगाउन चाहने कुरामा बदल्न क्रिएटरहरूमा भर पर्छन्। Kolab ले उनीहरूलाई सिधै जोड्छ।',
      overviewHeading: 'नेपालका फेसन ब्रान्डहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'नेपालको फेसन बजार स्थानीय बुटिक लेबल र सिलाई घरहरूदेखि छिटो बढिरहेका अनलाइन कपडा पसलहरूसम्म फैलिएको छ, र आउटफिट सामग्री — स्टाइलिङ, ट्राई-अन हल, पर्व लुक — ले स्थिर उत्पादन तस्बिरहरूभन्दा निरन्तर राम्रो प्रदर्शन गर्छ।',
        'Kolab ले कपडा ब्रान्ड, बुटिक, र डिजाइनरहरूलाई ब्रान्डको आफ्नै पेज फलो गर्नेमा मात्र भर पर्नुको सट्टा सौन्दर्य र प्लेटफर्मअनुसार फेसन क्रिएटरहरू फेला पार्ने तरिका दिन्छ।',
      ],
      secondHeading: 'Kolab मा फेसन क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का फेसन क्रिएटरहरूले Instagram र TikTok मा स्टाइलिङ भिडियो, ट्राई-अन हल, पर्व र विवाह-सिजन लुक, र ब्रान्ड ट्राई-अन पोस्ट गर्छन्, जुन ब्युटी र लाइफस्टाइलसँगै फेसन श्रेणीअन्तर्गत सूचीबद्ध हुन्छन्।',
        'कपडा ब्रान्डले सिजनल कलेक्सन सुरुवातको वरिपरि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ, वा स्टाइल गरिएको सामग्रीको बदलामा प्रोडक्ट प्रस्ताव गर्ने निःशुल्क खुला इभेन्ट पोस्ट गर्न सक्छ।',
      ],
      trustParagraph: 'प्रोडक्टमा आधारित फेसन सहकार्यहरू तलबसहितका जस्तै उही तरिकाले प्रमाणित हुन्छन् — क्रिएटरको पहिचान जाँचिन्छ, र कुनै पनि तलबसहितको बजेट सहमत सामग्री डेलिभर र स्वीकृत नभएसम्म एस्क्रोमा राखिन्छ।',
      relatedExtra: { label: 'Instagram क्रिएटरहरू', path: '/instagram-creators', description: 'आउटफिट र स्टाइलिङ सामग्री Instagram रिल र क्यारोसेलका लागि बनेको हो।' },
      ctaHeading: 'नेपालमा फेसन इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका फेसन क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'beauty-influencers-nepal',
    icon: Sparkles,
    keywords: ['beauty influencers Nepal', 'beauty creators Nepal', 'makeup influencers Nepal', 'skincare influencers Nepal'],
    label: { en: 'beauty influencers', ne: 'ब्युटी इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Beauty Influencers in Nepal | Hire Skincare & Makeup Creators',
      seoDescription: 'Hire beauty influencers in Nepal on Kolab — creators covering skincare routines, makeup tutorials, and salon or cosmetic brand reviews.',
      breadcrumbName: 'Beauty Influencers',
      eyebrow: 'Beauty Influencers Nepal',
      heading: 'Beauty Influencers in Nepal',
      intro: "Skincare routines, makeup tutorials, and honest product reviews drive real purchase decisions in Nepal's growing beauty market. Kolab connects cosmetic brands and salons with the creators shaping those decisions.",
      overviewHeading: "Why beauty content matters in Nepal's cosmetics market",
      overviewParagraphs: [
        'Beauty and skincare brands in Nepal compete in a market where trust matters more than glossy advertising — a creator showing a genuine before-and-after or a real routine carries more weight than a studio ad.',
        'Kolab connects cosmetic brands, skincare lines, and salons with beauty creators who post that kind of content regularly, so a product launch reaches an audience already primed to care.',
      ],
      secondHeading: 'What beauty creators cover on Kolab',
      secondParagraphs: [
        'Beauty creators on Kolab post skincare routines, makeup tutorials, product reviews, and salon or spa experiences across Instagram, TikTok, and YouTube, listed under the Beauty category alongside Fashion and Lifestyle.',
        'Brands can post a paid review campaign, a product-seeding open event, or an ongoing ambassador-style partnership for a new line.',
      ],
      trustParagraph: 'Beauty partnerships on Kolab run through the same identity verification and escrow-protected payments as every category, so product-seeding and paid review campaigns both have a clear, safe process.',
      relatedExtra: { label: 'TikTok Creators', path: '/tiktok-creators', description: 'Quick tutorials and routines are a strong fit for TikTok.' },
      ctaHeading: 'Find Beauty Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with beauty creators across Nepal.',
    },
    ne: {
      seoTitle: 'Beauty Influencers in Nepal | Hire Skincare & Makeup Creators',
      seoDescription: 'Hire beauty influencers in Nepal on Kolab — creators covering skincare routines, makeup tutorials, and salon or cosmetic brand reviews.',
      breadcrumbName: 'ब्युटी इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका ब्युटी इन्फ्लुएन्सरहरू',
      heading: 'नेपालका ब्युटी इन्फ्लुएन्सरहरू',
      intro: 'स्किनकेयर रुटिन, मेकअप ट्युटोरियल, र इमानदार प्रोडक्ट समीक्षाले नेपालको बढिरहेको ब्युटी बजारमा वास्तविक खरिद निर्णयहरू चलाउँछन्। Kolab ले कस्मेटिक ब्रान्ड र सलुनहरूलाई ती निर्णयहरू आकार दिने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालको कस्मेटिक बजारमा ब्युटी सामग्री किन महत्त्वपूर्ण छ',
      overviewParagraphs: [
        'नेपालका ब्युटी र स्किनकेयर ब्रान्डहरू यस्तो बजारमा प्रतिस्पर्धा गर्छन् जहाँ चम्किलो विज्ञापनभन्दा भरोसाले धेरै महत्त्व राख्छ — साँचो बिफोर-आफ्टर वा वास्तविक रुटिन देखाउने क्रिएटरले स्टुडियो विज्ञापनभन्दा बढी वजन बोक्छ।',
        'Kolab ले कस्मेटिक ब्रान्ड, स्किनकेयर लाइन, र सलुनहरूलाई त्यस्तै सामग्री नियमित रूपमा पोस्ट गर्ने ब्युटी क्रिएटरहरूसँग जोड्छ, ताकि प्रोडक्ट सुरुवातले पहिले नै ख्याल गर्न तयार दर्शकसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा ब्युटी क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का ब्युटी क्रिएटरहरूले Instagram, TikTok, र YouTube मा स्किनकेयर रुटिन, मेकअप ट्युटोरियल, प्रोडक्ट समीक्षा, र सलुन वा स्पा अनुभव पोस्ट गर्छन्, जुन फेसन र लाइफस्टाइलसँगै ब्युटी श्रेणीअन्तर्गत सूचीबद्ध हुन्छन्।',
        'ब्रान्डहरूले तलबसहितको समीक्षा क्याम्पेन, प्रोडक्ट-सिडिङ खुला इभेन्ट, वा नयाँ लाइनका लागि निरन्तर एम्बासडर-शैलीको साझेदारी पोस्ट गर्न सक्छन्।',
      ],
      trustParagraph: 'Kolab मा ब्युटी साझेदारीहरू अन्य सबै श्रेणी जस्तै उही पहिचान प्रमाणीकरण र एस्क्रो-सुरक्षित भुक्तानीबाट गुज्र्छन्, त्यसैले प्रोडक्ट-सिडिङ र तलबसहितका समीक्षा क्याम्पेन दुवैको स्पष्ट, सुरक्षित प्रक्रिया हुन्छ।',
      relatedExtra: { label: 'TikTok क्रिएटरहरू', path: '/tiktok-creators', description: 'छिटो ट्युटोरियल र रुटिनहरू TikTok का लागि उपयुक्त हुन्छन्।' },
      ctaHeading: 'नेपालमा ब्युटी इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका ब्युटी क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'fitness-influencers-nepal',
    icon: Dumbbell,
    keywords: ['fitness influencers Nepal', 'fitness creators Nepal', 'gym influencers Nepal', 'yoga influencers Nepal'],
    label: { en: 'fitness influencers', ne: 'फिटनेस इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Fitness Influencers in Nepal | Hire Gym & Wellness Creators',
      seoDescription: 'Hire fitness influencers in Nepal on Kolab — creators covering gym content, home workouts, yoga, and nutrition for fitness brands and gyms.',
      breadcrumbName: 'Fitness Influencers',
      eyebrow: 'Fitness Influencers Nepal',
      heading: 'Fitness Influencers in Nepal',
      intro: "Gym culture, home workouts, and yoga content have built loyal followings across Nepali social media. Kolab connects gyms, supplement brands, and fitness apparel with creators who train and post consistently.",
      overviewHeading: "Why fitness brands in Nepal need creator partnerships",
      overviewParagraphs: [
        "Gyms, sports nutrition brands, and activewear labels in Nepal are competing for attention in a category where demonstrated results matter — a creator's own transformation or workout routine sells harder than a stock photo of dumbbells.",
        'Kolab connects those brands with fitness creators covering strength training, yoga, home workouts, and nutrition, so a gym membership drive or a supplement launch reaches people already following fitness content.',
      ],
      secondHeading: 'What fitness creators cover on Kolab',
      secondParagraphs: [
        'Fitness creators on Kolab post workout routines, gym reviews, yoga sessions, and nutrition content across Instagram, YouTube, and TikTok, listed under Fitness & Health alongside Sports and Lifestyle.',
        'A gym can post a paid campaign for a membership drive, a supplement brand can run a product-review campaign, or a studio can offer a free open event — class access in exchange for content.',
      ],
      trustParagraph: 'Fitness partnerships — including free gym access or product seeding — run through the same verified-creator, escrow-protected process as every category on Kolab.',
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'Full workout routines and nutrition breakdowns suit longer YouTube content.' },
      ctaHeading: 'Find Fitness Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with fitness creators across Nepal.',
    },
    ne: {
      seoTitle: 'Fitness Influencers in Nepal | Hire Gym & Wellness Creators',
      seoDescription: 'Hire fitness influencers in Nepal on Kolab — creators covering gym content, home workouts, yoga, and nutrition for fitness brands and gyms.',
      breadcrumbName: 'फिटनेस इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका फिटनेस इन्फ्लुएन्सरहरू',
      heading: 'नेपालका फिटनेस इन्फ्लुएन्सरहरू',
      intro: 'जिम संस्कृति, घरमै गरिने वर्कआउट, र योग सामग्रीले नेपाली सामाजिक सञ्जालभर वफादार फलोअर बनाएका छन्। Kolab ले जिम, सप्लिमेन्ट ब्रान्ड, र फिटनेस पहिरन कम्पनीहरूलाई नियमित रूपमा अभ्यास गर्ने र पोस्ट गर्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका फिटनेस ब्रान्डहरूलाई किन क्रिएटर साझेदारी चाहिन्छ',
      overviewParagraphs: [
        'नेपालका जिम, स्पोर्ट्स न्युट्रिसन ब्रान्ड, र एक्टिवियर लेबलहरू यस्तो श्रेणीमा ध्यान तान्न प्रतिस्पर्धा गर्छन् जहाँ देखिने नतिजाले महत्त्व राख्छ — क्रिएटरको आफ्नै ट्रान्सफर्मेसन वा वर्कआउट रुटिनले डम्बलको स्टक फोटोभन्दा बढी बिक्री गराउँछ।',
        'Kolab ले ती ब्रान्डहरूलाई स्ट्रेन्थ ट्रेनिङ, योग, घरमै वर्कआउट, र पोषण समेट्ने फिटनेस क्रिएटरहरूसँग जोड्छ, ताकि जिम सदस्यता अभियान वा सप्लिमेन्ट सुरुवातले पहिले नै फिटनेस सामग्री फलो गरिरहेका मानिसहरूसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा फिटनेस क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का फिटनेस क्रिएटरहरूले Instagram, YouTube, र TikTok मा वर्कआउट रुटिन, जिम समीक्षा, योग सत्र, र पोषण सामग्री पोस्ट गर्छन्, जुन स्पोर्ट्स र लाइफस्टाइलसँगै फिटनेस र स्वास्थ्य अन्तर्गत सूचीबद्ध हुन्छन्।',
        'जिमले सदस्यता अभियानका लागि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ, सप्लिमेन्ट ब्रान्डले प्रोडक्ट-समीक्षा क्याम्पेन चलाउन सक्छ, वा स्टुडियोले निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छ — सामग्रीको बदलामा क्लास पहुँच।',
      ],
      trustParagraph: 'निःशुल्क जिम पहुँच वा प्रोडक्ट सिडिङ लगायत फिटनेस साझेदारीहरू Kolab मा हरेक श्रेणीका लागि उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट गुज्र्छन्।',
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'पूर्ण वर्कआउट रुटिन र पोषण विश्लेषण लामो YouTube सामग्रीका लागि उपयुक्त हुन्छन्।' },
      ctaHeading: 'नेपालमा फिटनेस इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका फिटनेस क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'tech-influencers-nepal',
    icon: Cpu,
    keywords: ['tech influencers Nepal', 'technology influencers Nepal', 'tech creators Nepal', 'gadget reviewers Nepal'],
    label: { en: 'tech influencers', ne: 'टेक इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Tech Influencers in Nepal | Hire Technology & Gadget Creators',
      seoDescription: 'Hire tech influencers in Nepal on Kolab — creators covering gadget reviews, app content, and technology news for tech brands and startups.',
      breadcrumbName: 'Tech Influencers',
      eyebrow: 'Tech Influencers Nepal',
      heading: 'Tech Influencers in Nepal',
      intro: "Gadget unboxings, app reviews, and Nepal's growing startup scene all have an audience on YouTube and Instagram. Kolab connects tech brands and startups with the creators covering that space.",
      overviewHeading: "Why tech brands and startups in Nepal need creators",
      overviewParagraphs: [
        "Phone launches, app releases, and local startup announcements move faster on a creator's channel than through a traditional press release — Nepali tech audiences follow reviewers and explainers for buying decisions.",
        'Kolab connects electronics retailers, app developers, and startups with tech creators covering reviews, comparisons, and app walkthroughs, instead of relying on scattered outreach.',
      ],
      secondHeading: 'What tech creators cover on Kolab',
      secondParagraphs: [
        'Tech creators on Kolab post gadget unboxings, phone and laptop reviews, app walkthroughs, and technology explainers across YouTube and Instagram, listed under the Technology category.',
        'A phone retailer can post a paid review campaign, an app can run a launch campaign for install-driving content, or a startup can offer a free open event around a product demo.',
      ],
      trustParagraph: 'Device loans, early-access app campaigns, and paid review budgets all run through the same verified-creator, escrow-protected process as every category on Kolab.',
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'In-depth reviews and comparisons are a natural fit for YouTube.' },
      ctaHeading: 'Find Tech Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with tech creators across Nepal.',
    },
    ne: {
      seoTitle: 'Tech Influencers in Nepal | Hire Technology & Gadget Creators',
      seoDescription: 'Hire tech influencers in Nepal on Kolab — creators covering gadget reviews, app content, and technology news for tech brands and startups.',
      breadcrumbName: 'टेक इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका टेक इन्फ्लुएन्सरहरू',
      heading: 'नेपालका टेक इन्फ्लुएन्सरहरू',
      intro: 'ग्याजेट अनबक्सिङ, एप समीक्षा, र नेपालको बढिरहेको स्टार्टअप दृश्य — यी सबैको YouTube र Instagram मा दर्शक छ। Kolab ले टेक ब्रान्ड र स्टार्टअपहरूलाई त्यो क्षेत्र समेट्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका टेक ब्रान्ड र स्टार्टअपहरूलाई किन क्रिएटर चाहिन्छ',
      overviewParagraphs: [
        'फोन सुरुवात, एप रिलिज, र स्थानीय स्टार्टअप घोषणाहरू परम्परागत प्रेस विज्ञप्तिभन्दा क्रिएटरको च्यानलमा छिटो चल्छन् — नेपाली टेक दर्शकले खरिद निर्णयका लागि समीक्षक र व्याख्याताहरू फलो गर्छन्।',
        'Kolab ले इलेक्ट्रोनिक्स रिटेलर, एप डेभलपर, र स्टार्टअपहरूलाई समीक्षा, तुलना, र एप वाकथ्रु समेट्ने टेक क्रिएटरहरूसँग जोड्छ, छरिएको आउटरिचमा भर पर्नुको सट्टा।',
      ],
      secondHeading: 'Kolab मा टेक क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का टेक क्रिएटरहरूले YouTube र Instagram मा ग्याजेट अनबक्सिङ, फोन र ल्यापटप समीक्षा, एप वाकथ्रु, र प्रविधि व्याख्या पोस्ट गर्छन्, जुन प्रविधि श्रेणीअन्तर्गत सूचीबद्ध हुन्छन्।',
        'फोन रिटेलरले तलबसहितको समीक्षा क्याम्पेन पोस्ट गर्न सक्छ, एपले इन्स्टल-चलाउने सामग्रीका लागि सुरुवात क्याम्पेन चलाउन सक्छ, वा स्टार्टअपले प्रोडक्ट डेमोको वरिपरि निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छ।',
      ],
      trustParagraph: 'डिभाइस ऋण, प्रारम्भिक-पहुँच एप क्याम्पेन, र तलबसहितका समीक्षा बजेट सबै Kolab मा हरेक श्रेणीका लागि उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट गुज्र्छन्।',
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'गहिरो समीक्षा र तुलनाहरू YouTube का लागि स्वाभाविक रूपमा उपयुक्त हुन्छन्।' },
      ctaHeading: 'नेपालमा टेक इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका टेक क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'finance-influencers-nepal',
    icon: Wallet,
    keywords: ['finance influencers Nepal', 'finfluencer Nepal', 'money creators Nepal', 'investing influencers Nepal'],
    label: { en: 'finance influencers', ne: 'फाइनान्स इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Finance Influencers in Nepal | Hire Finfluencers & Money Creators',
      seoDescription: 'Hire finance influencers in Nepal on Kolab — creators covering personal finance, digital payments, and investing content for fintech and finance brands.',
      breadcrumbName: 'Finance Influencers',
      eyebrow: 'Finance Influencers Nepal',
      heading: 'Finance Influencers in Nepal',
      intro: "Digital wallets, stock market investing, and personal-finance literacy are growing topics on Nepali social media. Kolab connects fintech companies and finance brands with the creators explaining that world.",
      overviewHeading: 'Why finance brands in Nepal work with creators',
      overviewParagraphs: [
        "As digital payments and retail investing have grown in Nepal, a small but engaged group of creators has built audiences explaining budgeting, saving, and the local stock market (NEPSE) in plain language — a format banks and fintech apps struggle to replicate on their own channels.",
        'Kolab connects fintech apps, banks, and insurance or investment brands with those creators, so a product explainer or a financial-literacy campaign reaches people who are already listening.',
      ],
      secondHeading: 'What finance creators cover on Kolab',
      secondParagraphs: [
        'Finance creators on Kolab post budgeting tips, digital-wallet and app walkthroughs, and investing basics across YouTube and Instagram, listed under the Finance category.',
        'A fintech app can post a paid campaign for an app-explainer series, or a bank can run a financial-literacy content partnership.',
      ],
      trustParagraph: 'Finance-related campaigns are held to the same verification and escrow standards as every category on Kolab, which matters even more in a category where audience trust is the whole point.',
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'Explainer-style finance content performs well as longer YouTube videos.' },
      ctaHeading: 'Find Finance Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with finance creators across Nepal.',
    },
    ne: {
      seoTitle: 'Finance Influencers in Nepal | Hire Finfluencers & Money Creators',
      seoDescription: 'Hire finance influencers in Nepal on Kolab — creators covering personal finance, digital payments, and investing content for fintech and finance brands.',
      breadcrumbName: 'फाइनान्स इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका फाइनान्स इन्फ्लुएन्सरहरू',
      heading: 'नेपालका फाइनान्स इन्फ्लुएन्सरहरू',
      intro: 'डिजिटल वालेट, सेयर बजार लगानी, र व्यक्तिगत-वित्त साक्षरता नेपाली सामाजिक सञ्जालमा बढ्दो विषयहरू हुन्। Kolab ले फिनटेक कम्पनी र वित्त ब्रान्डहरूलाई त्यो संसार व्याख्या गर्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका वित्त ब्रान्डहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'नेपालमा डिजिटल भुक्तानी र खुद्रा लगानी बढेसँगै, सजिलो भाषामा बजेट, बचत, र स्थानीय सेयर बजार (NEPSE) व्याख्या गर्दै एउटा सानो तर संलग्न क्रिएटर समूहले दर्शक बनाएको छ — यस्तो ढाँचा जुन बैंक र फिनटेक एपहरूले आफ्नै च्यानलमा दोहोर्‍याउन गाह्रो पाउँछन्।',
        'Kolab ले फिनटेक एप, बैंक, र बीमा वा लगानी ब्रान्डहरूलाई ती क्रिएटरहरूसँग जोड्छ, ताकि प्रोडक्ट व्याख्या वा वित्तीय-साक्षरता क्याम्पेनले पहिले नै सुन्दै गरेका मानिसहरूसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा वित्त क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का वित्त क्रिएटरहरूले YouTube र Instagram मा बजेटिङ सुझाव, डिजिटल-वालेट र एप वाकथ्रु, र लगानीका आधारभूत कुरा पोस्ट गर्छन्, जुन वित्त श्रेणीअन्तर्गत सूचीबद्ध हुन्छन्।',
        'फिनटेक एपले एप-व्याख्या शृंखलाका लागि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ, वा बैंकले वित्तीय-साक्षरता सामग्री साझेदारी चलाउन सक्छ।',
      ],
      trustParagraph: 'वित्त-सम्बन्धी क्याम्पेनहरू Kolab मा हरेक श्रेणी जस्तै उही प्रमाणीकरण र एस्क्रो मापदण्डमा राखिन्छन्, जुन त्यस्तो श्रेणीमा झन् महत्त्वपूर्ण हुन्छ जहाँ दर्शकको भरोसा नै सबथोक हो।',
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'व्याख्यात्मक-शैलीको वित्त सामग्रीले लामो YouTube भिडियोका रूपमा राम्रो प्रदर्शन गर्छ।' },
      ctaHeading: 'नेपालमा फाइनान्स इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका वित्त क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'education-influencers-nepal',
    icon: GraduationCap,
    keywords: ['education influencers Nepal', 'education creators Nepal', 'study abroad influencers Nepal', 'exam prep influencers Nepal'],
    label: { en: 'education influencers', ne: 'शिक्षा इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Education Influencers in Nepal | Hire Study & Exam Prep Creators',
      seoDescription: 'Hire education influencers in Nepal on Kolab — creators covering SEE and +2 exam prep, study tips, and study-abroad content for schools and consultancies.',
      breadcrumbName: 'Education Influencers',
      eyebrow: 'Education Influencers Nepal',
      heading: 'Education Influencers in Nepal',
      intro: "SEE and +2 exam prep, study-abroad guidance, and coaching-center reviews all have dedicated audiences among Nepali students. Kolab connects schools, consultancies, and edtech brands with creators covering that space.",
      overviewHeading: 'Why education brands in Nepal need creators',
      overviewParagraphs: [
        "Study-abroad consultancies, coaching centers, and edtech apps compete for the attention of students who increasingly research decisions — which country, which consultancy, which exam strategy — through creator content rather than brochures alone.",
        'Kolab connects those brands with education creators posting exam tips, study-abroad journeys, and coaching reviews, so a consultancy or coaching center reaches students already engaging with that content.',
      ],
      secondHeading: 'What education creators cover on Kolab',
      secondParagraphs: [
        'Education creators on Kolab post exam prep tips, study-abroad vlogs, coaching and course reviews, and study-technique content across YouTube and Instagram, listed under the Education category.',
        'A consultancy can post a paid campaign around an admissions season, or a coaching center can offer a free open event — course access in exchange for a review series.',
      ],
      trustParagraph: 'Education campaigns follow the same verified-creator, escrow-protected process as every category, which matters given how much students rely on this content for high-stakes decisions.',
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'Long-form exam prep and study-abroad guides suit YouTube well.' },
      ctaHeading: 'Find Education Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with education creators across Nepal.',
    },
    ne: {
      seoTitle: 'Education Influencers in Nepal | Hire Study & Exam Prep Creators',
      seoDescription: 'Hire education influencers in Nepal on Kolab — creators covering SEE and +2 exam prep, study tips, and study-abroad content for schools and consultancies.',
      breadcrumbName: 'शिक्षा इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका शिक्षा इन्फ्लुएन्सरहरू',
      heading: 'नेपालका शिक्षा इन्फ्लुएन्सरहरू',
      intro: 'SEE र +2 परीक्षा तयारी, विदेश अध्ययन मार्गदर्शन, र कोचिङ-सेन्टर समीक्षा — यी सबैका नेपाली विद्यार्थीहरूमा समर्पित दर्शक छन्। Kolab ले स्कुल, कन्सल्टेन्सी, र एडटेक ब्रान्डहरूलाई त्यो क्षेत्र समेट्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका शिक्षा ब्रान्डहरूलाई किन क्रिएटर चाहिन्छ',
      overviewParagraphs: [
        'विदेश अध्ययन कन्सल्टेन्सी, कोचिङ सेन्टर, र एडटेक एपहरू यस्ता विद्यार्थीहरूको ध्यानका लागि प्रतिस्पर्धा गर्छन् जसले निर्णयहरू — कुन देश, कुन कन्सल्टेन्सी, कुन परीक्षा रणनीति — बढ्दो रूपमा एक्लै ब्रोसरभन्दा क्रिएटर सामग्रीमार्फत खोजी गर्छन्।',
        'Kolab ले ती ब्रान्डहरूलाई परीक्षा सुझाव, विदेश अध्ययन यात्रा, र कोचिङ समीक्षा पोस्ट गर्ने शिक्षा क्रिएटरहरूसँग जोड्छ, ताकि कन्सल्टेन्सी वा कोचिङ सेन्टरले पहिले नै त्यस्तो सामग्रीसँग जोडिएका विद्यार्थीहरूसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा शिक्षा क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का शिक्षा क्रिएटरहरूले YouTube र Instagram मा परीक्षा तयारी सुझाव, विदेश अध्ययन भ्लग, कोचिङ र कोर्स समीक्षा, र अध्ययन-प्रविधि सामग्री पोस्ट गर्छन्, जुन शिक्षा श्रेणीअन्तर्गत सूचीबद्ध हुन्छन्।',
        'कन्सल्टेन्सीले भर्ना सिजनको वरिपरि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ, वा कोचिङ सेन्टरले निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छ — समीक्षा शृंखलाको बदलामा कोर्स पहुँच।',
      ],
      trustParagraph: 'शिक्षा क्याम्पेनहरूले हरेक श्रेणी जस्तै उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रिया पछ्याउँछन्, जुन विद्यार्थीहरूले उच्च-दांव निर्णयका लागि यो सामग्रीमा कति भर पर्छन् भन्ने कुरामा महत्त्वपूर्ण हुन्छ।',
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'लामो-फर्म परीक्षा तयारी र विदेश अध्ययन गाइडहरू YouTube का लागि उपयुक्त हुन्छन्।' },
      ctaHeading: 'नेपालमा शिक्षा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका शिक्षा क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'gaming-influencers-nepal',
    icon: Gamepad2,
    keywords: ['gaming influencers Nepal', 'gaming creators Nepal', 'esports influencers Nepal', 'streamers Nepal'],
    label: { en: 'gaming influencers', ne: 'गेमिङ इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Gaming Influencers in Nepal | Hire Esports & Mobile Gaming Creators',
      seoDescription: 'Hire gaming influencers in Nepal on Kolab — creators covering mobile esports, game streaming, and gaming-gear reviews for gaming and tech brands.',
      breadcrumbName: 'Gaming Influencers',
      eyebrow: 'Gaming Influencers Nepal',
      heading: 'Gaming Influencers in Nepal',
      intro: "Mobile esports and streaming have built a large, engaged gaming audience in Nepal. Kolab connects gaming brands, cyber cafes, and tech companies with the creators and streamers driving that scene.",
      overviewHeading: "Why gaming brands in Nepal work with creators",
      overviewParagraphs: [
        "Mobile titles have turned casual play into a competitive, watched scene in Nepal, with streamers and tournament players building sizable followings on YouTube, Facebook, and TikTok.",
        'Kolab connects gaming-gear brands, mobile game publishers, and cyber cafes or gaming lounges with gaming creators, so a product launch or a tournament sponsorship reaches an audience that\'s already watching.',
      ],
      secondHeading: 'What gaming creators cover on Kolab',
      secondParagraphs: [
        'Gaming creators on Kolab stream and post gameplay, gear reviews, and tournament content across YouTube, Facebook, and TikTok, listed under the Gaming category.',
        'A gaming-gear brand can post a paid review campaign, or a mobile game publisher can run a launch campaign built around creator gameplay content.',
      ],
      trustParagraph: 'Gear sponsorships, paid streams, and tournament partnerships all run through the same verified-creator, escrow-protected process as every category on Kolab.',
      relatedExtra: { label: 'Facebook Creators', path: '/facebook-creators', description: 'Live gameplay and gaming clips have a strong following on Facebook in Nepal.' },
      ctaHeading: 'Find Gaming Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with gaming creators across Nepal.',
    },
    ne: {
      seoTitle: 'Gaming Influencers in Nepal | Hire Esports & Mobile Gaming Creators',
      seoDescription: 'Hire gaming influencers in Nepal on Kolab — creators covering mobile esports, game streaming, and gaming-gear reviews for gaming and tech brands.',
      breadcrumbName: 'गेमिङ इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका गेमिङ इन्फ्लुएन्सरहरू',
      heading: 'नेपालका गेमिङ इन्फ्लुएन्सरहरू',
      intro: 'मोबाइल इस्पोर्ट्स र स्ट्रिमिङले नेपालमा ठूलो, संलग्न गेमिङ दर्शक बनाएको छ। Kolab ले गेमिङ ब्रान्ड, साइबर क्याफे, र टेक कम्पनीहरूलाई त्यो दृश्य चलाउने क्रिएटर र स्ट्रिमरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका गेमिङ ब्रान्डहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'मोबाइल गेमहरूले नेपालमा साधारण खेललाई प्रतिस्पर्धात्मक, हेरिने दृश्यमा बदलेको छ, जहाँ स्ट्रिमर र टुर्नामेन्ट खेलाडीहरूले YouTube, Facebook, र TikTok मा ठूलो फलोअर बनाएका छन्।',
        'Kolab ले गेमिङ-गियर ब्रान्ड, मोबाइल गेम प्रकाशक, र साइबर क्याफे वा गेमिङ लाउन्जहरूलाई गेमिङ क्रिएटरहरूसँग जोड्छ, ताकि प्रोडक्ट सुरुवात वा टुर्नामेन्ट प्रायोजनले पहिले नै हेरिरहेका दर्शकसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा गेमिङ क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का गेमिङ क्रिएटरहरूले YouTube, Facebook, र TikTok मा गेमप्ले स्ट्रिम र पोस्ट गर्छन्, गियर समीक्षा गर्छन्, र टुर्नामेन्ट सामग्री बनाउँछन्, जुन गेमिङ श्रेणीअन्तर्गत सूचीबद्ध हुन्छन्।',
        'गेमिङ-गियर ब्रान्डले तलबसहितको समीक्षा क्याम्पेन पोस्ट गर्न सक्छ, वा मोबाइल गेम प्रकाशकले क्रिएटर गेमप्ले सामग्रीमा आधारित सुरुवात क्याम्पेन चलाउन सक्छ।',
      ],
      trustParagraph: 'गियर प्रायोजन, तलबसहितका स्ट्रिम, र टुर्नामेन्ट साझेदारी सबै Kolab मा हरेक श्रेणीका लागि उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट गुज्र्छन्।',
      relatedExtra: { label: 'Facebook क्रिएटरहरू', path: '/facebook-creators', description: 'लाइभ गेमप्ले र गेमिङ क्लिपहरूको नेपालमा Facebook मा बलियो फलोअर छ।' },
      ctaHeading: 'नेपालमा गेमिङ इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका गेमिङ क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'automobile-influencers-nepal',
    icon: Car,
    keywords: ['automobile influencers Nepal', 'auto influencers Nepal', 'bike review creators Nepal', 'car influencers Nepal'],
    label: { en: 'automobile influencers', ne: 'अटोमोबाइल इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Automobile Influencers in Nepal | Hire Car & Bike Review Creators',
      seoDescription: 'Hire automobile influencers in Nepal on Kolab — creators covering bike and car reviews, test rides, and auto-brand content.',
      breadcrumbName: 'Automobile Influencers',
      eyebrow: 'Automobile Influencers Nepal',
      heading: 'Automobile Influencers in Nepal',
      intro: "Bike and car reviews, test rides, and comparison videos have a dedicated audience among Nepali buyers weighing a big purchase. Kolab connects dealerships and auto brands with the creators they trust.",
      overviewHeading: 'Why auto brands in Nepal need creator reviews',
      overviewParagraphs: [
        "Vehicles are a major purchase in Nepal, and buyers increasingly research bikes and cars through independent review creators before visiting a showroom — mileage, road performance, and honest pros and cons carry more weight than a brochure spec sheet.",
        'Kolab connects dealerships, auto brands, and accessory shops with creators who cover test rides and comparisons, so a new launch reaches buyers already in research mode.',
      ],
      secondHeading: 'What automobile creators cover on Kolab',
      secondParagraphs: [
        'Automobile creators on Kolab post test-ride reviews, comparison videos, and road-trip content across YouTube and Facebook, most closely matched under the Technology and Lifestyle categories.',
        'A dealership can post a paid campaign around a new model launch, or offer a free open event — a test ride in exchange for a review video.',
      ],
      trustParagraph: 'Test-ride loans and paid review campaigns run through the same verified-creator, escrow-protected process as every category on Kolab.',
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'Detailed test-ride and comparison reviews suit longer YouTube videos.' },
      ctaHeading: 'Find Automobile Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with automobile creators across Nepal.',
    },
    ne: {
      seoTitle: 'Automobile Influencers in Nepal | Hire Car & Bike Review Creators',
      seoDescription: 'Hire automobile influencers in Nepal on Kolab — creators covering bike and car reviews, test rides, and auto-brand content.',
      breadcrumbName: 'अटोमोबाइल इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका अटोमोबाइल इन्फ्लुएन्सरहरू',
      heading: 'नेपालका अटोमोबाइल इन्फ्लुएन्सरहरू',
      intro: 'बाइक र कार समीक्षा, टेस्ट राइड, र तुलनात्मक भिडियोहरूको ठूलो खरिदको तौल गरिरहेका नेपाली खरिदकर्ताहरूमा समर्पित दर्शक छ। Kolab ले डिलरसिप र अटो ब्रान्डहरूलाई उनीहरूले भरोसा गर्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका अटो ब्रान्डहरूलाई किन क्रिएटर समीक्षा चाहिन्छ',
      overviewParagraphs: [
        'नेपालमा सवारी साधन ठूलो खरिद हो, र खरिदकर्ताहरूले शोरूम भ्रमण गर्नुअघि बढ्दो रूपमा स्वतन्त्र समीक्षा क्रिएटरहरूमार्फत बाइक र कार खोजी गर्छन् — माइलेज, सडक प्रदर्शन, र इमानदार गुण-दोषले ब्रोसर स्पेक शीटभन्दा बढी वजन बोक्छ।',
        'Kolab ले डिलरसिप, अटो ब्रान्ड, र एक्सेसरी पसलहरूलाई टेस्ट राइड र तुलना समेट्ने क्रिएटरहरूसँग जोड्छ, ताकि नयाँ सुरुवातले पहिले नै खोजी अवस्थामा रहेका खरिदकर्ताहरूसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा अटोमोबाइल क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का अटोमोबाइल क्रिएटरहरूले YouTube र Facebook मा टेस्ट-राइड समीक्षा, तुलनात्मक भिडियो, र रोड-ट्रिप सामग्री पोस्ट गर्छन्, जुन प्रविधि र लाइफस्टाइल श्रेणीहरूसँग सबैभन्दा नजिक मिल्छन्।',
        'डिलरसिपले नयाँ मोडेल सुरुवातको वरिपरि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ, वा निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छ — समीक्षा भिडियोको बदलामा टेस्ट राइड।',
      ],
      trustParagraph: 'टेस्ट-राइड ऋण र तलबसहितका समीक्षा क्याम्पेनहरू Kolab मा हरेक श्रेणीका लागि उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट गुज्र्छन्।',
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'विस्तृत टेस्ट-राइड र तुलना समीक्षाहरू लामो YouTube भिडियोका लागि उपयुक्त हुन्छन्।' },
      ctaHeading: 'नेपालमा अटोमोबाइल इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका अटोमोबाइल क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'hotel-influencers-nepal',
    icon: BedDouble,
    keywords: ['hotel influencers Nepal', 'hospitality influencers Nepal', 'hotel creators Nepal', 'resort influencers Nepal'],
    label: { en: 'hotel influencers', ne: 'होटल इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Hotel Influencers in Nepal | Hire Hospitality & Stay Creators',
      seoDescription: 'Hire hotel influencers in Nepal on Kolab — creators covering hotel and resort stays, hospitality reviews, and destination content.',
      breadcrumbName: 'Hotel Influencers',
      eyebrow: 'Hotel Influencers Nepal',
      heading: 'Hotel Influencers in Nepal',
      intro: "A hotel stay documented well is one of the strongest booking drivers in tourism. Kolab connects hotels and resorts across Nepal with creators who cover stays, amenities, and guest experiences.",
      overviewHeading: 'Why hotels in Nepal work with creators',
      overviewParagraphs: [
        'Hotel and resort bookings increasingly follow a creator\'s room tour or stay vlog rather than a listing photo alone — guests want to see the actual room, the view, the breakfast, before booking.',
        'Kolab connects hotels, resorts, and boutique stays across Nepal with creators who produce that kind of stay content, whether it\'s a Pokhara lakeside resort or a Kathmandu boutique hotel.',
      ],
      secondHeading: 'What hotel and hospitality creators cover on Kolab',
      secondParagraphs: [
        'Hospitality creators on Kolab post stay vlogs, room tours, and amenity reviews across Instagram and YouTube, closely matched under the Travel category.',
        'A hotel can post a free open event — a complimentary stay in exchange for content — or a paid campaign for an ongoing content partnership around a new property or season.',
      ],
      trustParagraph: 'Complimentary-stay collaborations and paid campaigns both go through Kolab\'s verified-creator and escrow-protected process, so hotels know who they\'re hosting and creators know they\'ll be paid as agreed.',
      relatedExtra: { label: 'Travel Influencers', path: '/travel-influencers-nepal', description: 'Hotel stays are a core part of travel content on Kolab.' },
      ctaHeading: 'Find Hotel Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with hospitality creators across Nepal.',
    },
    ne: {
      seoTitle: 'Hotel Influencers in Nepal | Hire Hospitality & Stay Creators',
      seoDescription: 'Hire hotel influencers in Nepal on Kolab — creators covering hotel and resort stays, hospitality reviews, and destination content.',
      breadcrumbName: 'होटल इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका होटल इन्फ्लुएन्सरहरू',
      heading: 'नेपालका होटल इन्फ्लुएन्सरहरू',
      intro: 'राम्रोसँग कागजात गरिएको होटल बसाइ पर्यटनमा सबैभन्दा बलियो बुकिङ ड्राइभरहरूमध्ये एक हो। Kolab ले नेपालभरका होटल र रिसोर्टहरूलाई बसाइ, सुविधा, र पाहुना अनुभव समेट्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका होटलहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'होटल र रिसोर्ट बुकिङहरू बढ्दो रूपमा एक्लै लिस्टिङ तस्बिरभन्दा क्रिएटरको कोठा भ्रमण वा बसाइ भ्लग पछ्याउँछन् — पाहुनाहरूले बुक गर्नुअघि वास्तविक कोठा, दृश्य, र बिहानको खाजा हेर्न चाहन्छन्।',
        'Kolab ले नेपालभरका होटल, रिसोर्ट, र बुटिक बसाइहरूलाई त्यस्तै बसाइ सामग्री उत्पादन गर्ने क्रिएटरहरूसँग जोड्छ, चाहे त्यो पोखराको ताल किनारको रिसोर्ट होस् वा काठमाडौंको बुटिक होटल।',
      ],
      secondHeading: 'Kolab मा होटल र आतिथ्य क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का आतिथ्य क्रिएटरहरूले Instagram र YouTube मा बसाइ भ्लग, कोठा भ्रमण, र सुविधा समीक्षा पोस्ट गर्छन्, जुन ट्राभल श्रेणीसँग सबैभन्दा नजिक मिल्छन्।',
        'होटलले निःशुल्क खुला इभेन्ट पोस्ट गर्न सक्छ — सामग्रीको बदलामा निःशुल्क बसाइ — वा नयाँ प्रोपर्टी वा सिजनको वरिपरि निरन्तर सामग्री साझेदारीका लागि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ।',
      ],
      trustParagraph: 'निःशुल्क-बसाइ सहकार्य र तलबसहितका क्याम्पेन दुवै Kolab को प्रमाणित-क्रिएटर र एस्क्रो-सुरक्षित प्रक्रियामार्फत जान्छन्, त्यसैले होटलहरूलाई थाहा हुन्छ उनीहरूले कसलाई होस्ट गरिरहेका छन्, र क्रिएटरहरूलाई थाहा हुन्छ उनीहरूले सहमतिअनुसार भुक्तानी पाउनेछन्।',
      relatedExtra: { label: 'ट्राभल इन्फ्लुएन्सरहरू', path: '/travel-influencers-nepal', description: 'होटल बसाइ Kolab मा ट्राभल सामग्रीको मुख्य भाग हो।' },
      ctaHeading: 'नेपालमा होटल इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका आतिथ्य क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'restaurant-influencers-nepal',
    icon: ChefHat,
    keywords: ['restaurant influencers Nepal', 'restaurant creators Nepal', 'cafe influencers Nepal', 'dining influencers Nepal'],
    label: { en: 'restaurant influencers', ne: 'रेस्टुरेन्ट इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Restaurant Influencers in Nepal | Hire Cafe & Dining Creators',
      seoDescription: 'Hire restaurant influencers in Nepal on Kolab — creators covering restaurant reviews, cafe visits, and menu launches for dining brands.',
      breadcrumbName: 'Restaurant Influencers',
      eyebrow: 'Restaurant Influencers Nepal',
      heading: 'Restaurant Influencers in Nepal',
      intro: "A new restaurant or cafe in Kathmandu, Pokhara, or Lalitpur lives or dies on the first wave of reviews and recommendations. Kolab connects dining brands with the creators who shape that first impression.",
      overviewHeading: 'Why restaurants in Nepal work with creators',
      overviewParagraphs: [
        "With cafe culture booming across Nepal's cities, restaurant openings and menu launches increasingly rely on creator visits and reviews to build early buzz rather than traditional advertising alone.",
        'Kolab helps restaurants, cafes, and dining brands find creators who post that kind of review and visit content consistently, matched to their location and cuisine.',
      ],
      secondHeading: 'What restaurant creators cover on Kolab',
      secondParagraphs: [
        'Restaurant and cafe creators on Kolab post visit vlogs, menu reviews, and ambience content across Instagram reels and TikTok, listed under Food & Beverage.',
        'A restaurant can post a free open event — a complimentary meal in exchange for coverage — or a paid campaign for a launch or ongoing content partnership.',
      ],
      trustParagraph: 'Complimentary-meal collaborations and paid campaigns both run through Kolab\'s verified-creator and escrow-protected process, keeping restaurant partnerships straightforward and accountable.',
      relatedExtra: { label: 'Food Influencers', path: '/food-influencers-nepal', description: 'Restaurant and food content overlap closely on Kolab.' },
      ctaHeading: 'Find Restaurant Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with restaurant creators across Nepal.',
    },
    ne: {
      seoTitle: 'Restaurant Influencers in Nepal | Hire Cafe & Dining Creators',
      seoDescription: 'Hire restaurant influencers in Nepal on Kolab — creators covering restaurant reviews, cafe visits, and menu launches for dining brands.',
      breadcrumbName: 'रेस्टुरेन्ट इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका रेस्टुरेन्ट इन्फ्लुएन्सरहरू',
      heading: 'नेपालका रेस्टुरेन्ट इन्फ्लुएन्सरहरू',
      intro: 'काठमाडौं, पोखरा, वा ललितपुरमा नयाँ रेस्टुरेन्ट वा क्याफे समीक्षा र सिफारिसका पहिलो लहरमै बाँच्छ वा मर्छ। Kolab ले त्यो पहिलो प्रभाव आकार दिने क्रिएटरहरूसँग डाइनिङ ब्रान्डहरूलाई जोड्छ।',
      overviewHeading: 'नेपालका रेस्टुरेन्टहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'नेपालका सहरहरूभर क्याफे संस्कृति फस्टाइरहेकाले, रेस्टुरेन्ट सुरुवात र मेनु लन्चहरू परम्परागत विज्ञापनमा मात्र भर नपरी सुरुवाती चर्चा बनाउन क्रिएटर भ्रमण र समीक्षामा बढ्दो रूपमा भर पर्छन्।',
        'Kolab ले रेस्टुरेन्ट, क्याफे, र डाइनिङ ब्रान्डहरूलाई उनीहरूको स्थान र परिकारसँग मिल्दो त्यस्तै समीक्षा र भ्रमण सामग्री निरन्तर पोस्ट गर्ने क्रिएटरहरू फेला पार्न मद्दत गर्छ।',
      ],
      secondHeading: 'Kolab मा रेस्टुरेन्ट क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का रेस्टुरेन्ट र क्याफे क्रिएटरहरूले Instagram रिल र TikTok मा भ्रमण भ्लग, मेनु समीक्षा, र वातावरण सामग्री पोस्ट गर्छन्, जुन खाना र पेय अन्तर्गत सूचीबद्ध हुन्छन्।',
        'रेस्टुरेन्टले निःशुल्क खुला इभेन्ट पोस्ट गर्न सक्छ — कभरेजको बदलामा निःशुल्क खाना — वा सुरुवात वा निरन्तर सामग्री साझेदारीका लागि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ।',
      ],
      trustParagraph: 'निःशुल्क-खाना सहकार्य र तलबसहितका क्याम्पेन दुवै Kolab को प्रमाणित-क्रिएटर र एस्क्रो-सुरक्षित प्रक्रियामार्फत जान्छन्, जसले रेस्टुरेन्ट साझेदारीलाई सोझो र जवाफदेही राख्छ।',
      relatedExtra: { label: 'खाना इन्फ्लुएन्सरहरू', path: '/food-influencers-nepal', description: 'Kolab मा रेस्टुरेन्ट र खाना सामग्री नजिकैबाट मिल्दछन्।' },
      ctaHeading: 'नेपालमा रेस्टुरेन्ट इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका रेस्टुरेन्ट क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'healthcare-influencers-nepal',
    icon: HeartPulse,
    keywords: ['healthcare influencers Nepal', 'health influencers Nepal', 'wellness creators Nepal', 'health creators Nepal'],
    label: { en: 'healthcare influencers', ne: 'स्वास्थ्य इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Healthcare Influencers in Nepal | Hire Wellness & Health Creators',
      seoDescription: 'Hire healthcare influencers in Nepal on Kolab — creators covering wellness, mental health awareness, and clinic or health-brand content.',
      breadcrumbName: 'Healthcare Influencers',
      eyebrow: 'Healthcare Influencers Nepal',
      heading: 'Healthcare Influencers in Nepal',
      intro: "Wellness and mental-health awareness content has grown steadily on Nepali social media. Kolab connects clinics, health brands, and wellness businesses with creators covering that space responsibly.",
      overviewHeading: 'Why health and wellness brands in Nepal work with creators',
      overviewParagraphs: [
        'As conversations around mental health, general wellness, and preventive care have opened up in Nepal, a growing group of creators has built audiences around approachable, non-clinical health content — a tone traditional healthcare advertising often misses.',
        'Kolab connects clinics, wellness centers, and health-product brands with those creators, so a wellness campaign reaches an audience that already engages with the topic.',
      ],
      secondHeading: 'What healthcare and wellness creators cover on Kolab',
      secondParagraphs: [
        'Wellness creators on Kolab post general health tips, mental-health awareness content, and product or service reviews across Instagram and YouTube, most closely matched under Fitness & Health and Lifestyle.',
        'A clinic or wellness brand can post a paid awareness campaign, or offer a free open event around a service trial in exchange for honest coverage.',
      ],
      trustParagraph: 'Health-related content carries extra responsibility, and Kolab\'s creator verification and escrow-protected payments apply the same way here as in every category — identity checked, budgets held until approved work is delivered.',
      relatedExtra: { label: 'Fitness Influencers', path: '/fitness-influencers-nepal', description: 'Wellness and fitness content overlap closely on Kolab.' },
      ctaHeading: 'Find Healthcare Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with wellness creators across Nepal.',
    },
    ne: {
      seoTitle: 'Healthcare Influencers in Nepal | Hire Wellness & Health Creators',
      seoDescription: 'Hire healthcare influencers in Nepal on Kolab — creators covering wellness, mental health awareness, and clinic or health-brand content.',
      breadcrumbName: 'स्वास्थ्य इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका स्वास्थ्य इन्फ्लुएन्सरहरू',
      heading: 'नेपालका स्वास्थ्य इन्फ्लुएन्सरहरू',
      intro: 'नेपाली सामाजिक सञ्जालमा वेलनेस र मानसिक-स्वास्थ्य सचेतना सामग्री स्थिर रूपमा बढेको छ। Kolab ले क्लिनिक, स्वास्थ्य ब्रान्ड, र वेलनेस व्यवसायहरूलाई त्यो क्षेत्र जिम्मेवारीपूर्वक समेट्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका स्वास्थ्य र वेलनेस ब्रान्डहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'नेपालमा मानसिक स्वास्थ्य, सामान्य वेलनेस, र रोकथाम हेरचाहका बारेमा कुराकानी खुलेसँगै, सहज, गैर-क्लिनिकल स्वास्थ्य सामग्रीको वरिपरि दर्शक बनाउने क्रिएटरहरूको समूह बढिरहेको छ — परम्परागत स्वास्थ्य विज्ञापनले प्रायः छुटाउने खालको स्वर।',
        'Kolab ले क्लिनिक, वेलनेस सेन्टर, र स्वास्थ्य-प्रोडक्ट ब्रान्डहरूलाई ती क्रिएटरहरूसँग जोड्छ, ताकि वेलनेस क्याम्पेनले पहिले नै त्यो विषयसँग जोडिएका दर्शकसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा स्वास्थ्य र वेलनेस क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का वेलनेस क्रिएटरहरूले Instagram र YouTube मा सामान्य स्वास्थ्य सुझाव, मानसिक-स्वास्थ्य सचेतना सामग्री, र प्रोडक्ट वा सेवा समीक्षा पोस्ट गर्छन्, जुन फिटनेस र स्वास्थ्य तथा लाइफस्टाइलसँग सबैभन्दा नजिक मिल्छन्।',
        'क्लिनिक वा वेलनेस ब्रान्डले तलबसहितको सचेतना क्याम्पेन पोस्ट गर्न सक्छ, वा इमानदार कभरेजको बदलामा सेवा परीक्षणको वरिपरि निःशुल्क खुला इभेन्ट प्रस्ताव गर्न सक्छ।',
      ],
      trustParagraph: 'स्वास्थ्य-सम्बन्धी सामग्रीले अतिरिक्त जिम्मेवारी बोक्छ, र Kolab को क्रिएटर प्रमाणीकरण र एस्क्रो-सुरक्षित भुक्तानी हरेक श्रेणीमा जस्तै यहाँ पनि उस्तै लागू हुन्छ — पहिचान जाँचिन्छ, स्वीकृत काम डेलिभर नभएसम्म बजेट राखिन्छ।',
      relatedExtra: { label: 'फिटनेस इन्फ्लुएन्सरहरू', path: '/fitness-influencers-nepal', description: 'Kolab मा वेलनेस र फिटनेस सामग्री नजिकैबाट मिल्दछन्।' },
      ctaHeading: 'नेपालमा स्वास्थ्य इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका वेलनेस क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
  {
    slug: 'real-estate-influencers-nepal',
    icon: Building2,
    keywords: ['real estate influencers Nepal', 'property influencers Nepal', 'real estate creators Nepal', 'property content creators Nepal'],
    label: { en: 'real estate influencers', ne: 'घरजग्गा इन्फ्लुएन्सरहरू' },
    en: {
      seoTitle: 'Real Estate Influencers in Nepal | Hire Property Content Creators',
      seoDescription: 'Hire real estate influencers in Nepal on Kolab — creators covering property tours, apartment reviews, and real-estate content in Kathmandu Valley and beyond.',
      breadcrumbName: 'Real Estate Influencers',
      eyebrow: 'Real Estate Influencers Nepal',
      heading: 'Real Estate Influencers in Nepal',
      intro: "Apartment tours and property walkthroughs help buyers and renters make decisions long before a site visit. Kolab connects real estate developers and agents with creators who produce that content.",
      overviewHeading: 'Why real estate brands in Nepal work with creators',
      overviewParagraphs: [
        "As apartment and housing developments have expanded across the Kathmandu Valley and other growing cities, buyers and renters increasingly want a video walkthrough before committing to a site visit — something static listing photos can't provide.",
        'Kolab connects developers, real estate agents, and property brands with creators who produce property tours and area guides, so a new listing or project reaches serious, research-stage buyers.',
      ],
      secondHeading: 'What real estate creators cover on Kolab',
      secondParagraphs: [
        'Real estate creators on Kolab post property walkthroughs, apartment reviews, and neighborhood guides across YouTube and Instagram, most closely matched under the Home & Living category.',
        'A developer can post a paid campaign for a project launch, or a real estate agency can run an ongoing content partnership covering multiple listings.',
      ],
      trustParagraph: 'Property-tour campaigns run through the same verified-creator, escrow-protected process as every category on Kolab, which matters for a category involving high-value listings and site access.',
      relatedExtra: { label: 'YouTube Creators', path: '/youtube-creators', description: 'Full property walkthroughs suit longer YouTube videos.' },
      ctaHeading: 'Find Real Estate Influencers in Nepal',
      ctaSub: 'Download Kolab to connect with real estate creators across Nepal.',
    },
    ne: {
      seoTitle: 'Real Estate Influencers in Nepal | Hire Property Content Creators',
      seoDescription: 'Hire real estate influencers in Nepal on Kolab — creators covering property tours, apartment reviews, and real-estate content in Kathmandu Valley and beyond.',
      breadcrumbName: 'घरजग्गा इन्फ्लुएन्सरहरू',
      eyebrow: 'नेपालका घरजग्गा इन्फ्लुएन्सरहरू',
      heading: 'नेपालका घरजग्गा इन्फ्लुएन्सरहरू',
      intro: 'अपार्टमेन्ट भ्रमण र प्रोपर्टी वाकथ्रुले खरिदकर्ता र भाडामा लिनेहरूलाई साइट भ्रमणभन्दा धेरै अगाडि नै निर्णय लिन मद्दत गर्छ। Kolab ले घरजग्गा विकासकर्ता र एजेन्टहरूलाई त्यो सामग्री उत्पादन गर्ने क्रिएटरहरूसँग जोड्छ।',
      overviewHeading: 'नेपालका घरजग्गा ब्रान्डहरूले किन क्रिएटरहरूसँग काम गर्छन्',
      overviewParagraphs: [
        'काठमाडौं उपत्यका र अन्य बढिरहेका सहरहरूभर अपार्टमेन्ट र आवास विकासहरू विस्तार भएसँगै, खरिदकर्ता र भाडामा लिनेहरू साइट भ्रमणमा प्रतिबद्ध हुनुअघि भिडियो वाकथ्रु चाहन्छन् — जुन स्थिर लिस्टिङ तस्बिरले दिन सक्दैन।',
        'Kolab ले विकासकर्ता, घरजग्गा एजेन्ट, र प्रोपर्टी ब्रान्डहरूलाई प्रोपर्टी भ्रमण र क्षेत्र गाइड उत्पादन गर्ने क्रिएटरहरूसँग जोड्छ, ताकि नयाँ लिस्टिङ वा प्रोजेक्टले गम्भीर, खोजी-चरणका खरिदकर्ताहरूसम्म पुग्छ।',
      ],
      secondHeading: 'Kolab मा घरजग्गा क्रिएटरहरूले के समेट्छन्',
      secondParagraphs: [
        'Kolab का घरजग्गा क्रिएटरहरूले YouTube र Instagram मा प्रोपर्टी वाकथ्रु, अपार्टमेन्ट समीक्षा, र छिमेक गाइड पोस्ट गर्छन्, जुन घर र जीवनयापन श्रेणीसँग सबैभन्दा नजिक मिल्छन्।',
        'विकासकर्ताले प्रोजेक्ट सुरुवातका लागि तलबसहितको क्याम्पेन पोस्ट गर्न सक्छ, वा घरजग्गा एजेन्सीले धेरै लिस्टिङ समेट्ने निरन्तर सामग्री साझेदारी चलाउन सक्छ।',
      ],
      trustParagraph: 'प्रोपर्टी-भ्रमण क्याम्पेनहरू Kolab मा हरेक श्रेणीका लागि उही प्रमाणित-क्रिएटर, एस्क्रो-सुरक्षित प्रक्रियाबाट गुज्र्छन्, जुन उच्च-मूल्यका लिस्टिङ र साइट पहुँच समावेश भएको श्रेणीका लागि महत्त्वपूर्ण हुन्छ।',
      relatedExtra: { label: 'YouTube क्रिएटरहरू', path: '/youtube-creators', description: 'पूर्ण प्रोपर्टी वाकथ्रुहरू लामो YouTube भिडियोका लागि उपयुक्त हुन्छन्।' },
      ctaHeading: 'नेपालमा घरजग्गा इन्फ्लुएन्सरहरू फेला पार्नुहोस्',
      ctaSub: 'नेपालभरका घरजग्गा क्रिएटरहरूसँग जोडिन Kolab डाउनलोड गर्नुहोस्।',
    },
  },
];
