import type { IconType } from 'react-icons';
import {
  FaUtensils, FaCoffee, FaHamburger, FaWineGlassAlt, FaMotorcycle,
  FaPlane, FaMountain, FaHotel, FaConciergeBell, FaSuitcase, FaPassport, FaCompass, FaMapMarkerAlt,
  FaTshirt, FaSpa, FaMagic, FaGem, FaRing,
  FaDumbbell, FaFutbol, FaHeartbeat, FaHiking, FaSwimmer, FaBicycle, FaRunning,
  FaGamepad, FaMicrochip, FaMobileAlt, FaLaptop, FaWifi, FaRocket, FaHeadphones,
  FaGraduationCap, FaBook, FaChalkboardTeacher,
  FaLeaf, FaHome, FaCouch, FaBed, FaBroom, FaBath, FaTree, FaSeedling,
  FaMusic, FaPalette, FaFilm, FaTheaterMasks, FaCamera, FaVideo, FaGuitar, FaDrum, FaPaintRoller,
  FaPaw, FaDog, FaCat, FaBaby, FaCar, FaTaxi, FaShip, FaSubway,
  FaWallet, FaMoneyBillWave, FaCoins, FaCreditCard, FaPiggyBank, FaHandHoldingUsd, FaChartLine,
  FaRecycle, FaSun, FaCloud, FaUmbrellaBeach, FaSnowflake, FaFire, FaBolt,
  FaShoppingCart, FaStore, FaBox, FaTag, FaTags, FaGift, FaTruck,
  FaCalendarAlt, FaStar, FaHeart, FaGlobe, FaLightbulb, FaShieldAlt, FaKey, FaLock,
  FaBriefcase, FaBriefcaseMedical, FaUsers, FaUser, FaHandshake,
  FaInstagram, FaTiktok, FaYoutube, FaTwitter, FaFacebook,
  FaWrench, FaHammer, FaChair, FaBullseye, FaBuilding, FaTrophy,
} from 'react-icons/fa';

export interface IconOption {
  slug: string;
  label: string;
  Icon: IconType;
}

/** Curated FontAwesome5 icons — slug matches the icon name mobile's
 *  `<FontAwesome5 name="...">` expects, so admin-picked icons render
 *  identically across web and mobile. */
export const ICON_OPTIONS: IconOption[] = [
  { slug: 'utensils', label: 'Food', Icon: FaUtensils },
  { slug: 'coffee', label: 'Coffee / Cafe', Icon: FaCoffee },
  { slug: 'hamburger', label: 'Fast Food', Icon: FaHamburger },
  { slug: 'wine-glass-alt', label: 'Wine / Drinks', Icon: FaWineGlassAlt },
  { slug: 'motorcycle', label: 'Delivery', Icon: FaMotorcycle },
  { slug: 'plane', label: 'Travel / Flights', Icon: FaPlane },
  { slug: 'mountain', label: 'Adventure', Icon: FaMountain },
  { slug: 'hotel', label: 'Hotel', Icon: FaHotel },
  { slug: 'concierge-bell', label: 'Hospitality', Icon: FaConciergeBell },
  { slug: 'suitcase', label: 'Suitcase', Icon: FaSuitcase },
  { slug: 'passport', label: 'Passport', Icon: FaPassport },
  { slug: 'compass', label: 'Compass', Icon: FaCompass },
  { slug: 'map-marker-alt', label: 'Location', Icon: FaMapMarkerAlt },
  { slug: 'tshirt', label: 'Fashion', Icon: FaTshirt },
  { slug: 'spa', label: 'Beauty / Spa', Icon: FaSpa },
  { slug: 'magic', label: 'Skincare / Magic', Icon: FaMagic },
  { slug: 'gem', label: 'Jewelry', Icon: FaGem },
  { slug: 'ring', label: 'Ring', Icon: FaRing },
  { slug: 'dumbbell', label: 'Fitness', Icon: FaDumbbell },
  { slug: 'futbol', label: 'Sports', Icon: FaFutbol },
  { slug: 'heartbeat', label: 'Wellness / Health', Icon: FaHeartbeat },
  { slug: 'hiking', label: 'Hiking', Icon: FaHiking },
  { slug: 'swimmer', label: 'Swimming', Icon: FaSwimmer },
  { slug: 'bicycle', label: 'Cycling', Icon: FaBicycle },
  { slug: 'running', label: 'Running', Icon: FaRunning },
  { slug: 'gamepad', label: 'Gaming', Icon: FaGamepad },
  { slug: 'microchip', label: 'Technology', Icon: FaMicrochip },
  { slug: 'mobile-alt', label: 'Mobile / Gadgets', Icon: FaMobileAlt },
  { slug: 'laptop', label: 'Laptop', Icon: FaLaptop },
  { slug: 'wifi', label: 'Wifi / Internet', Icon: FaWifi },
  { slug: 'rocket', label: 'Startup / Launch', Icon: FaRocket },
  { slug: 'headphones', label: 'Audio', Icon: FaHeadphones },
  { slug: 'graduation-cap', label: 'Education', Icon: FaGraduationCap },
  { slug: 'book', label: 'Book', Icon: FaBook },
  { slug: 'chalkboard-teacher', label: 'Teaching', Icon: FaChalkboardTeacher },
  { slug: 'leaf', label: 'Lifestyle / Nature', Icon: FaLeaf },
  { slug: 'home', label: 'Home & Living', Icon: FaHome },
  { slug: 'couch', label: 'Furniture', Icon: FaCouch },
  { slug: 'bed', label: 'Bedroom', Icon: FaBed },
  { slug: 'broom', label: 'Cleaning', Icon: FaBroom },
  { slug: 'bath', label: 'Bath', Icon: FaBath },
  { slug: 'tree', label: 'Tree / Outdoors', Icon: FaTree },
  { slug: 'seedling', label: 'Sustainability', Icon: FaSeedling },
  { slug: 'music', label: 'Music', Icon: FaMusic },
  { slug: 'palette', label: 'Art & Design', Icon: FaPalette },
  { slug: 'film', label: 'Film & TV', Icon: FaFilm },
  { slug: 'theater-masks', label: 'Entertainment', Icon: FaTheaterMasks },
  { slug: 'camera', label: 'Photography', Icon: FaCamera },
  { slug: 'video', label: 'Video', Icon: FaVideo },
  { slug: 'guitar', label: 'Guitar', Icon: FaGuitar },
  { slug: 'drum', label: 'Drum', Icon: FaDrum },
  { slug: 'paint-roller', label: 'Painting', Icon: FaPaintRoller },
  { slug: 'paw', label: 'Pets', Icon: FaPaw },
  { slug: 'dog', label: 'Dog', Icon: FaDog },
  { slug: 'cat', label: 'Cat', Icon: FaCat },
  { slug: 'baby', label: 'Parenting', Icon: FaBaby },
  { slug: 'car', label: 'Automotive', Icon: FaCar },
  { slug: 'taxi', label: 'Taxi', Icon: FaTaxi },
  { slug: 'ship', label: 'Cruise / Shipping', Icon: FaShip },
  { slug: 'subway', label: 'Transit', Icon: FaSubway },
  { slug: 'wallet', label: 'Finance', Icon: FaWallet },
  { slug: 'money-bill-wave', label: 'Payments', Icon: FaMoneyBillWave },
  { slug: 'coins', label: 'Coins', Icon: FaCoins },
  { slug: 'credit-card', label: 'Credit Card', Icon: FaCreditCard },
  { slug: 'piggy-bank', label: 'Savings', Icon: FaPiggyBank },
  { slug: 'hand-holding-usd', label: 'Funding', Icon: FaHandHoldingUsd },
  { slug: 'chart-line', label: 'Growth / Analytics', Icon: FaChartLine },
  { slug: 'recycle', label: 'Sustainability', Icon: FaRecycle },
  { slug: 'sun', label: 'Sun / Summer', Icon: FaSun },
  { slug: 'cloud', label: 'Cloud', Icon: FaCloud },
  { slug: 'umbrella-beach', label: 'Beach', Icon: FaUmbrellaBeach },
  { slug: 'snowflake', label: 'Winter', Icon: FaSnowflake },
  { slug: 'fire', label: 'Fire / Trending', Icon: FaFire },
  { slug: 'bolt', label: 'Energy', Icon: FaBolt },
  { slug: 'shopping-cart', label: 'Retail / E-commerce', Icon: FaShoppingCart },
  { slug: 'store', label: 'Store', Icon: FaStore },
  { slug: 'box', label: 'Product', Icon: FaBox },
  { slug: 'tag', label: 'Tag', Icon: FaTag },
  { slug: 'tags', label: 'Discount / Offer', Icon: FaTags },
  { slug: 'gift', label: 'Gift / Festival', Icon: FaGift },
  { slug: 'truck', label: 'Shipping', Icon: FaTruck },
  { slug: 'calendar-alt', label: 'Event', Icon: FaCalendarAlt },
  { slug: 'star', label: 'Featured / Star', Icon: FaStar },
  { slug: 'heart', label: 'Favorites', Icon: FaHeart },
  { slug: 'globe', label: 'Global', Icon: FaGlobe },
  { slug: 'lightbulb', label: 'Ideas', Icon: FaLightbulb },
  { slug: 'shield-alt', label: 'Security', Icon: FaShieldAlt },
  { slug: 'key', label: 'Key', Icon: FaKey },
  { slug: 'lock', label: 'Lock', Icon: FaLock },
  { slug: 'briefcase', label: 'Business', Icon: FaBriefcase },
  { slug: 'briefcase-medical', label: 'Healthcare', Icon: FaBriefcaseMedical },
  { slug: 'users', label: 'Community', Icon: FaUsers },
  { slug: 'user', label: 'Person', Icon: FaUser },
  { slug: 'handshake', label: 'Partnership', Icon: FaHandshake },
  { slug: 'instagram', label: 'Instagram', Icon: FaInstagram },
  { slug: 'tiktok', label: 'TikTok', Icon: FaTiktok },
  { slug: 'youtube', label: 'YouTube', Icon: FaYoutube },
  { slug: 'twitter', label: 'Twitter / X', Icon: FaTwitter },
  { slug: 'facebook', label: 'Facebook', Icon: FaFacebook },
  { slug: 'wrench', label: 'Tools / Repair', Icon: FaWrench },
  { slug: 'hammer', label: 'Construction', Icon: FaHammer },
  { slug: 'chair', label: 'Chair', Icon: FaChair },
  { slug: 'bullseye', label: 'Target / Goal', Icon: FaBullseye },
  { slug: 'building', label: 'Real Estate', Icon: FaBuilding },
  { slug: 'trophy', label: 'Awards', Icon: FaTrophy },
];

const BY_SLUG = new Map(ICON_OPTIONS.map((o) => [o.slug, o]));

export function getIconOption(slug: string): IconOption | undefined {
  return BY_SLUG.get(slug);
}
